In [1]:
import numpy as np
import pandas as pd

In [25]:
data = [[1.3,6.2,7.3,], [4.2,8.1,0.3], [3.7,1.1,2.8], [13.2,8.2,3.1,], [1.3,5.1,3.9], [3.2,4.1,12.5]]

heading = ['a', 'b', 'c']

ohe_data = np.array([[0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 0, 1],
 [0, 1, 0, 0, 0]])

classes = np.array([b'g', b'q', b'w', b'z', b't'])

In [59]:
new_data = np.array([1.3,6.2,7.3,4.2,8.1,43.5])
for i in range(len(classes)):
    classed_data = np.array([])
    
    print(i)
    boolean_mask = [np.argmax(y)==i for y in ohe_data]
    print(boolean_mask)
    print(new_data[[np.argmax(y)==i for y in ohe_data]])

0
[False, True, False, False, False, False]
[6.2]
1
[False, False, False, False, False, True]
[43.5]
2
[False, False, True, True, False, False]
[7.3 4.2]
3
[True, False, False, False, False, False]
[1.3]
4
[False, False, False, False, True, False]
[8.1]


In [30]:
y_class = [classes[np.argmax(i)] for i in ohe_data]

print(y_class)
print(type(y_class[0]))

In [27]:
df = pd.DataFrame(data = data, columns = heading)
print(df)

In [34]:
df['class'] = y_class

In [35]:
df

a    b     c class
0   1.3  6.2   7.3  b'z'
1   4.2  8.1   0.3  b'g'
2   3.7  1.1   2.8  b'w'
3  13.2  8.2   3.1  b'w'
4   1.3  5.1   3.9  b't'
5   3.2  4.1  12.5  b'q'

In [37]:
print(df.dtypes)

a        float64
b        float64
c        float64
class     object
dtype: object


In [42]:
df['class']==classes[4]

0    False
1    False
2    False
3    False
4     True
5    False
Name: class, dtype: bool

In [43]:
df.to_csv('newtest.csv', index=False)
df_reloaded = pd.read_csv('newtest.csv', nrows = None)
print(df_reloaded)

      a    b     c class
0   1.3  6.2   7.3  b'z'
1   4.2  8.1   0.3  b'g'
2   3.7  1.1   2.8  b'w'
3  13.2  8.2   3.1  b'w'
4   1.3  5.1   3.9  b't'
5   3.2  4.1  12.5  b'q'


In [44]:
df_reloaded['class']==classes[4]

0    False
1    False
2    False
3    False
4    False
5    False
Name: class, dtype: bool

In [52]:
df = pd.DataFrame(data = data, columns = heading)
df['class'] = y_class
print(df)

print('\n=====================\n')

positive_class = b't'

if positive_class is not None:
  df["class"] = df["class"] == positive_class

print(df)

      a    b     c class
0   1.3  6.2   7.3  b'z'
1   4.2  8.1   0.3  b'g'
2   3.7  1.1   2.8  b'w'
3  13.2  8.2   3.1  b'w'
4   1.3  5.1   3.9  b't'
5   3.2  4.1  12.5  b'q'


      a    b     c  class
0   1.3  6.2   7.3  False
1   4.2  8.1   0.3  False
2   3.7  1.1   2.8  False
3  13.2  8.2   3.1  False
4   1.3  5.1   3.9   True
5   3.2  4.1  12.5  False


In [55]:
df.to_csv('newtest.csv', index=False)

In [15]:
rand_data = np.random.rand(5,4,3)
#big_rand_data = np.random.rand(620000,50,16)
print(rand_data)

In [106]:
boolean_mask = rand_data[:, :, 1] > 0.5
structure_memory = boolean_mask.sum(axis=1)

In [128]:
print(boolean_mask)
print(structure_memory)
print(np.mean(structure_memory))

[[False False  True False]
 [ True  True False False]
 [ True False  True False]
 [ True  True False  True]
 [ True False False False]]
[1 2 2 3 1]
1.8


In [130]:
cut_data = np.split(rand_data[boolean_mask, :], np.cumsum(structure_memory)[:-1])

print(cut_data)
print('\n================\n')
cut_data = [jet_const for jet_const in cut_data if jet_const.size > 0]

print(cut_data)

[array([[0.24988476, 0.66179769, 0.40355534]]), array([[0.72456838, 0.57192137, 0.85048951],
       [0.68237374, 0.683802  , 0.48357035]]), array([[0.41145607, 0.56759926, 0.0114448 ],
       [0.98107084, 0.84257079, 0.54727676]]), array([[0.56003797, 0.80987209, 0.33581331],
       [0.29067496, 0.96770464, 0.18328952],
       [0.51969528, 0.72446184, 0.9759141 ]]), array([[0.82141664, 0.84996441, 0.96614358]])]


[array([[0.24988476, 0.66179769, 0.40355534]]), array([[0.72456838, 0.57192137, 0.85048951],
       [0.68237374, 0.683802  , 0.48357035]]), array([[0.41145607, 0.56759926, 0.0114448 ],
       [0.98107084, 0.84257079, 0.54727676]]), array([[0.56003797, 0.80987209, 0.33581331],
       [0.29067496, 0.96770464, 0.18328952],
       [0.51969528, 0.72446184, 0.9759141 ]]), array([[0.82141664, 0.84996441, 0.96614358]])]


In [131]:
max_constituents = 4
nb_constituents = np.array([])

for jet in range(len(cut_data)):
    if cut_data[jet].shape[0] >= max_constituents:
        nb_constituents = np.append(nb_constituents, max_constituents)
        cut_data[jet] = cut_data[jet][:max_constituents, :]
    else:
        nb_constituents = np.append(nb_constituents, cut_data[jet].shape[0])
        padding_length = max_constituents - cut_data[jet].shape[0]
        cut_data[jet] = np.pad(cut_data[jet], ((0, padding_length), (0, 0)))

print(np.asarray(cut_data))
print('\n===================\n')
print(nb_constituents)

[[[0.24988476 0.66179769 0.40355534]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 [[0.72456838 0.57192137 0.85048951]
  [0.68237374 0.683802   0.48357035]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 [[0.41145607 0.56759926 0.0114448 ]
  [0.98107084 0.84257079 0.54727676]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 [[0.56003797 0.80987209 0.33581331]
  [0.29067496 0.96770464 0.18328952]
  [0.51969528 0.72446184 0.9759141 ]
  [0.         0.         0.        ]]

 [[0.82141664 0.84996441 0.96614358]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]]


[1. 2. 2. 3. 1.]


In [20]:
ascending = False
order = ascending - (not ascending)
print(order)

-1


In [24]:
sorted_data = np.array([rand_data[i][(order*rand_data[i][:, 1]).argsort()] for i in range(len(rand_data))])
#big_sorted_data = np.asarray([big_rand_data[i][big_rand_data[i][:, 1].argsort()] for i in range(len(big_rand_data))])

print(sorted_data)
print(type(sorted_data))

[[[0.84295722 0.68112295 0.88595121]
  [0.81170426 0.64668738 0.13615513]
  [0.09873471 0.35589615 0.18897656]
  [0.21456516 0.35084943 0.15318961]]

 [[0.45495586 0.69656557 0.84959166]
  [0.66486354 0.66046301 0.13461521]
  [0.17863345 0.4991016  0.30361781]
  [0.48476333 0.11485154 0.93850134]]

 [[0.88156592 0.69492522 0.2367417 ]
  [0.61315008 0.68231606 0.42847928]
  [0.65656475 0.32341719 0.47568908]
  [0.93528146 0.12865657 0.47608832]]

 [[0.79419881 0.92269788 0.35957008]
  [0.04644044 0.85200478 0.12368693]
  [0.55604036 0.28871201 0.86119341]
  [0.35429345 0.16729886 0.91340971]]

 [[0.44284147 0.96856339 0.374811  ]
  [0.81302979 0.86802792 0.07247036]
  [0.64165009 0.70318422 0.63323774]
  [0.91882352 0.22272879 0.90367408]]]
<class 'numpy.ndarray'>


In [81]:
positive_class = 't'

In [85]:
bytes(positive_class, 'utf-8')

b't'

In [86]:
feature_labels = [
        "px",
        "py",
        "pz",
        "E",
        "E_rel",
        "pT",
        "pT_rel",
        "eta",
        "eta_rel",
        "eta_rot",
        "phi",
        "phi_rel",
        "phi_rot",
        "Delta_R",
        "cos(theta)",
        "cos(theta_rel)",
    ]

In [114]:
a = np.array([0,0,0,0])
print(a!=0)

[False False False False]


In [115]:
constituents_distribution = []
for jet in rand_data:
    const_nb = 0
    for const in jet:
        if const[0] != 0:
            const_nb += 1
    constituents_distribution.append(const_nb)

print(constituents_distribution)

[4, 4, 4, 4, 4]


In [6]:
np.arange(0,2,0.25)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75])

In [10]:
print(np.asarray(np.append(np.append(np.arange(0,2,0.25),np.arange(2,5,0.5)), np.arange(5,11,1))))

[ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.    2.5   3.    3.5
  4.    4.5   5.    6.    7.    8.    9.   10.  ]


In [7]:
import sys
import time

In [17]:
print('Starting process')

sys.stdout.write('\r')
# the exact output you're looking for:
sys.stdout.write("[%-20s] %d%%" % ('='*1, 5*1))
sys.stdout.flush()
time.sleep(0.5)

for i in range(2, 21):
    sys.stdout.write('\r')
    # the exact output you're looking for:
    sys.stdout.write("[%-20s] %d%%" % ('='*i, 5*i))
    sys.stdout.flush()
    time.sleep(0.5)

print('\nProcess complete')
    

Starting process
[====================] 100%
Process complete


In [15]:
a = 12
b= 'fish'

print(f'Hello {a}{b}')

Hello 12fish


In [72]:
a = np.array([[1]])
for i in range(4):
    a = np.concatenate((a,[[i]]), axis = 0)

print(a)

[[1]
 [0]
 [1]
 [2]
 [3]]


In [75]:
b = np.array([[9]])

for i in range(2,6):
    b = np.concatenate((b,[[i]]), axis = 0)

print(b)

[[9]
 [2]
 [3]
 [4]
 [5]]


In [74]:
print(np.concatenate((a,b), axis = 1))

[[1 9]
 [0 2]
 [1 3]
 [2 4]
 [3 5]]


In [4]:
c = np.array([])

for i in range(4):
    c = np.append(c, i)

print(c)

d = np.array([])

for i in range(5,9):
    d = np.append(d, i)

print(d)

e = np.concatenate(([c],[d]), axis =0)
print(e)

[0. 1. 2. 3.]
[5. 6. 7. 8.]
[[0. 1. 2. 3.]
 [5. 6. 7. 8.]]


In [5]:
np.swapaxes(e, 0, 1)

array([[0., 5.],
       [1., 6.],
       [2., 7.],
       [3., 8.]])

In [7]:
e[:,1]

array([1., 6.])

In [36]:
def combine_array(a1, a2):
    if np.ndim(a1) == 2:
        combined_array = np.concatenate((a1, [a2]), axis = 0)
    elif np.ndim(a1) == 1:
        combined_array = np.concatenate(([a1], [a2]), axis =1)

    return combined_array

In [32]:
f = np.array([])

f = np.concatenate(([f], [c]), axis = 1)
print(np.asarray(f))

f = np.concatenate((f,[d]), axis = 0)

print(np.asarray(f))

[[0. 1. 2. 3.]]
[[0. 1. 2. 3.]
 [5. 6. 7. 8.]]


In [28]:
np.ndim(c)

1

In [38]:
f = np.array([])

f = combine_array(f, c)
print(f)

f = combine_array(f,d)
print(f)

[[0. 1. 2. 3.]]
[[0. 1. 2. 3.]
 [5. 6. 7. 8.]]


In [5]:
import os

def get_file_paths(data_file_dir: str) -> list:
    """Gets path to the data files inside a given directory.

    Args:
        data_file_dir: Path to directory containing the data files.

    Returns:
        Array of paths to the data files themselves.
    """
    file_names = os.listdir(data_file_dir)
    print(file_names)
    file_paths = [os.path.join(data_file_dir, file_name) for file_name in file_names]

    return file_paths

In [6]:
get_file_paths('../Data/train/')

['jetImage_0_150p_40000_50000.h5', 'jetImage_4_150p_20000_30000.h5', 'jetImage_2_150p_50000_60000.h5', 'jetImage_5_150p_30000_40000.h5', 'jetImage_0_150p_70000_80000.h5', 'jetImage_3_150p_20000_30000.h5', 'jetImage_1_150p_0_10000.h5', 'jetImage_5_150p_50000_60000.h5', 'jetImage_2_150p_30000_40000.h5', 'jetImage_0_150p_0_10000.h5', 'jetImage_1_150p_80000_90000.h5', 'jetImage_1_150p_10000_20000.h5', 'jetImage_0_150p_60000_70000.h5', 'jetImage_6_150p_10000_20000.h5', 'jetImage_6_150p_80000_90000.h5', 'jetImage_0_150p_20000_30000.h5', 'jetImage_3_150p_70000_80000.h5', 'jetImage_1_150p_30000_40000.h5', 'jetImage_6_150p_50000_60000.h5', 'jetImage_3_150p_0_10000.h5', 'jetImage_4_150p_70000_80000.h5', 'jetImage_6_150p_30000_40000.h5', 'jetImage_1_150p_50000_60000.h5', 'jetImage_4_150p_40000_50000.h5', 'jetImage_3_150p_40000_50000.h5', 'jetImage_3_150p_60000_70000.h5', 'jetImage_5_150p_80000_90000.h5', 'jetImage_5_150p_10000_20000.h5', 'jetImage_2_150p_0_10000.h5', 'jetImage_4_150p_60000_70000.

['../Data/train/jetImage_0_150p_40000_50000.h5',
 '../Data/train/jetImage_4_150p_20000_30000.h5',
 '../Data/train/jetImage_2_150p_50000_60000.h5',
 '../Data/train/jetImage_5_150p_30000_40000.h5',
 '../Data/train/jetImage_0_150p_70000_80000.h5',
 '../Data/train/jetImage_3_150p_20000_30000.h5',
 '../Data/train/jetImage_1_150p_0_10000.h5',
 '../Data/train/jetImage_5_150p_50000_60000.h5',
 '../Data/train/jetImage_2_150p_30000_40000.h5',
 '../Data/train/jetImage_0_150p_0_10000.h5',
 '../Data/train/jetImage_1_150p_80000_90000.h5',
 '../Data/train/jetImage_1_150p_10000_20000.h5',
 '../Data/train/jetImage_0_150p_60000_70000.h5',
 '../Data/train/jetImage_6_150p_10000_20000.h5',
 '../Data/train/jetImage_6_150p_80000_90000.h5',
 '../Data/train/jetImage_0_150p_20000_30000.h5',
 '../Data/train/jetImage_3_150p_70000_80000.h5',
 '../Data/train/jetImage_1_150p_30000_40000.h5',
 '../Data/train/jetImage_6_150p_50000_60000.h5',
 '../Data/train/jetImage_3_150p_0_10000.h5',
 '../Data/train/jetImage_4_150p_

In [12]:
1%5

1

In [13]:
5%5

0

In [14]:
9%5

4

In [16]:
print('\rtest', flush = True)
print('\rcheese', flush = True)

test
cheese


In [36]:
from terminal_colors import tcols

a = True
print(tcols.FAIL+f'I just came to say {a*"hello"+(not a)*"goodbye"}'+tcols.ENDC)

I just came to say hello


In [1]:
def rah(fam:str='cheese'):
    print(fam)

In [2]:
rah()

cheese


In [3]:
rah('geezer')

geezer
