In [1]:
import numpy as np
import pandas as pd

In [25]:
data = [[1.3,6.2,7.3,], [4.2,8.1,0.3], [3.7,1.1,2.8], [13.2,8.2,3.1,], [1.3,5.1,3.9], [3.2,4.1,12.5]]

heading = ['a', 'b', 'c']

ohe_data = np.array([[0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 0, 1],
 [0, 1, 0, 0, 0]])

classes = np.array([b'g', b'q', b'w', b'z', b't'])

In [59]:
new_data = np.array([1.3,6.2,7.3,4.2,8.1,43.5])
for i in range(len(classes)):
    classed_data = np.array([])
    
    print(i)
    boolean_mask = [np.argmax(y)==i for y in ohe_data]
    print(boolean_mask)
    print(new_data[[np.argmax(y)==i for y in ohe_data]])

0
[False, True, False, False, False, False]
[6.2]
1
[False, False, False, False, False, True]
[43.5]
2
[False, False, True, True, False, False]
[7.3 4.2]
3
[True, False, False, False, False, False]
[1.3]
4
[False, False, False, False, True, False]
[8.1]


In [30]:
y_class = [classes[np.argmax(i)] for i in ohe_data]

print(y_class)
print(type(y_class[0]))

In [27]:
df = pd.DataFrame(data = data, columns = heading)
print(df)

In [34]:
df['class'] = y_class

In [35]:
df

a    b     c class
0   1.3  6.2   7.3  b'z'
1   4.2  8.1   0.3  b'g'
2   3.7  1.1   2.8  b'w'
3  13.2  8.2   3.1  b'w'
4   1.3  5.1   3.9  b't'
5   3.2  4.1  12.5  b'q'

In [37]:
print(df.dtypes)

a        float64
b        float64
c        float64
class     object
dtype: object


In [42]:
df['class']==classes[4]

0    False
1    False
2    False
3    False
4     True
5    False
Name: class, dtype: bool

In [43]:
df.to_csv('newtest.csv', index=False)
df_reloaded = pd.read_csv('newtest.csv', nrows = None)
print(df_reloaded)

      a    b     c class
0   1.3  6.2   7.3  b'z'
1   4.2  8.1   0.3  b'g'
2   3.7  1.1   2.8  b'w'
3  13.2  8.2   3.1  b'w'
4   1.3  5.1   3.9  b't'
5   3.2  4.1  12.5  b'q'


In [44]:
df_reloaded['class']==classes[4]

0    False
1    False
2    False
3    False
4    False
5    False
Name: class, dtype: bool

In [52]:
df = pd.DataFrame(data = data, columns = heading)
df['class'] = y_class
print(df)

print('\n=====================\n')

positive_class = b't'

if positive_class is not None:
  df["class"] = df["class"] == positive_class

print(df)

      a    b     c class
0   1.3  6.2   7.3  b'z'
1   4.2  8.1   0.3  b'g'
2   3.7  1.1   2.8  b'w'
3  13.2  8.2   3.1  b'w'
4   1.3  5.1   3.9  b't'
5   3.2  4.1  12.5  b'q'


      a    b     c  class
0   1.3  6.2   7.3  False
1   4.2  8.1   0.3  False
2   3.7  1.1   2.8  False
3  13.2  8.2   3.1  False
4   1.3  5.1   3.9   True
5   3.2  4.1  12.5  False


In [55]:
df.to_csv('newtest.csv', index=False)

In [2]:
rand_data = np.random.rand(5,4,3)
#big_rand_data = np.random.rand(620000,50,16)
print(rand_data)

[[[0.04108883 0.60510899 0.55045841]
  [0.28304357 0.31387414 0.19908185]
  [0.76101587 0.04065349 0.8713477 ]
  [0.56084251 0.46047315 0.90710192]]

 [[0.28719174 0.32373833 0.43248908]
  [0.48558394 0.73118686 0.38109807]
  [0.27189926 0.20372243 0.06806391]
  [0.30730507 0.14929012 0.01727189]]

 [[0.91080563 0.55202729 0.21296284]
  [0.42245012 0.97795339 0.48635419]
  [0.73144153 0.57345573 0.81114974]
  [0.54639047 0.35784027 0.51528999]]

 [[0.23974698 0.57094687 0.90082302]
  [0.02409681 0.67031098 0.26081909]
  [0.83198526 0.5557444  0.74678607]
  [0.68495935 0.75412091 0.65447643]]

 [[0.86678815 0.21325323 0.02867664]
  [0.59984007 0.05225387 0.51458407]
  [0.05298659 0.86795238 0.32037667]
  [0.22942537 0.12310337 0.17926765]]]


In [3]:
ascending = False
order = ascending - (not ascending)
print(order)

-1


In [4]:
sorted_data = np.array([rand_data[i][(order*rand_data[i][:, 1]).argsort()] for i in range(len(rand_data))])
#big_sorted_data = np.asarray([big_rand_data[i][big_rand_data[i][:, 1].argsort()] for i in range(len(big_rand_data))])

print(sorted_data)
print(type(sorted_data))

[[[0.04108883 0.60510899 0.55045841]
  [0.56084251 0.46047315 0.90710192]
  [0.28304357 0.31387414 0.19908185]
  [0.76101587 0.04065349 0.8713477 ]]

 [[0.48558394 0.73118686 0.38109807]
  [0.28719174 0.32373833 0.43248908]
  [0.27189926 0.20372243 0.06806391]
  [0.30730507 0.14929012 0.01727189]]

 [[0.42245012 0.97795339 0.48635419]
  [0.73144153 0.57345573 0.81114974]
  [0.91080563 0.55202729 0.21296284]
  [0.54639047 0.35784027 0.51528999]]

 [[0.68495935 0.75412091 0.65447643]
  [0.02409681 0.67031098 0.26081909]
  [0.23974698 0.57094687 0.90082302]
  [0.83198526 0.5557444  0.74678607]]

 [[0.05298659 0.86795238 0.32037667]
  [0.86678815 0.21325323 0.02867664]
  [0.22942537 0.12310337 0.17926765]
  [0.59984007 0.05225387 0.51458407]]]
<class 'numpy.ndarray'>


In [5]:
boolean_index = [True, False, False, True, False]

print(sorted_data[:,:,1][boolean_index].flatten())

[0.60510899 0.46047315 0.31387414 0.04065349 0.75412091 0.67031098
 0.57094687 0.5557444 ]


In [6]:
print(boolean_index)
print(1*(boolean_index))

[True, False, False, True, False]
[True, False, False, True, False]


In [7]:
boolean_mask = rand_data[:, :, 1] > 0.5
structure_memory = boolean_mask.sum(axis=1)

In [8]:
print(boolean_mask)
print(structure_memory)
print(np.mean(structure_memory))

[[ True False False False]
 [False  True False False]
 [ True  True  True False]
 [ True  True  True  True]
 [False False  True False]]
[1 1 3 4 1]
2.0


In [51]:
cut_data = np.split(rand_data[boolean_mask, :], np.cumsum(structure_memory)[:-1])

print(cut_data)
print('\n================\n')
cut_data = [jet_const for jet_const in cut_data if jet_const.size > 0]

print(cut_data)

[array([[0.04108883, 0.60510899, 0.55045841]]), array([[0.48558394, 0.73118686, 0.38109807]]), array([[0.91080563, 0.55202729, 0.21296284],
       [0.42245012, 0.97795339, 0.48635419],
       [0.73144153, 0.57345573, 0.81114974]]), array([[0.23974698, 0.57094687, 0.90082302],
       [0.02409681, 0.67031098, 0.26081909],
       [0.83198526, 0.5557444 , 0.74678607],
       [0.68495935, 0.75412091, 0.65447643]]), array([[0.05298659, 0.86795238, 0.32037667]])]


[array([[0.04108883, 0.60510899, 0.55045841]]), array([[0.48558394, 0.73118686, 0.38109807]]), array([[0.91080563, 0.55202729, 0.21296284],
       [0.42245012, 0.97795339, 0.48635419],
       [0.73144153, 0.57345573, 0.81114974]]), array([[0.23974698, 0.57094687, 0.90082302],
       [0.02409681, 0.67031098, 0.26081909],
       [0.83198526, 0.5557444 , 0.74678607],
       [0.68495935, 0.75412091, 0.65447643]]), array([[0.05298659, 0.86795238, 0.32037667]])]


In [52]:
max_constituents = 4
nb_constituents = np.array([])

for jet in range(len(cut_data)):
    if cut_data[jet].shape[0] >= max_constituents:
        nb_constituents = np.append(nb_constituents, max_constituents)
        cut_data[jet] = cut_data[jet][:max_constituents, :]
    else:
        nb_constituents = np.append(nb_constituents, cut_data[jet].shape[0])
        padding_length = max_constituents - cut_data[jet].shape[0]
        cut_data[jet] = np.pad(cut_data[jet], ((0, padding_length), (0, 0)), constant_values = -9.9)
print(np.asarray(cut_data))
print('\n===================\n')
print(nb_constituents)

[[[ 0.04108883  0.60510899  0.55045841]
  [-9.9        -9.9        -9.9       ]
  [-9.9        -9.9        -9.9       ]
  [-9.9        -9.9        -9.9       ]]

 [[ 0.48558394  0.73118686  0.38109807]
  [-9.9        -9.9        -9.9       ]
  [-9.9        -9.9        -9.9       ]
  [-9.9        -9.9        -9.9       ]]

 [[ 0.91080563  0.55202729  0.21296284]
  [ 0.42245012  0.97795339  0.48635419]
  [ 0.73144153  0.57345573  0.81114974]
  [-9.9        -9.9        -9.9       ]]

 [[ 0.23974698  0.57094687  0.90082302]
  [ 0.02409681  0.67031098  0.26081909]
  [ 0.83198526  0.5557444   0.74678607]
  [ 0.68495935  0.75412091  0.65447643]]

 [[ 0.05298659  0.86795238  0.32037667]
  [-9.9        -9.9        -9.9       ]
  [-9.9        -9.9        -9.9       ]
  [-9.9        -9.9        -9.9       ]]]


[1. 1. 3. 4. 1.]


In [48]:
is_not_padded = np.any(np.array(cut_data), axis = 2)
print(is_not_padded)
is_positive_class = [True, False, False, True, False]
print(is_positive_class)

[[ True  True  True False]
 [ True  True False False]
 [ True False False False]
 [ True  True  True False]
 [ True False False False]]
[True, False, False, True, False]


In [49]:
is_not_padded[is_positive_class]

array([[ True,  True,  True, False],
       [ True,  True,  True, False]])

In [51]:
print(np.array(cut_data)[is_positive_class][is_not_padded[is_positive_class]][:,1])

[0.74808507 0.53490341 0.5895019  0.77242777 0.89973615 0.92766441]


In [81]:
positive_class = 't'

In [85]:
bytes(positive_class, 'utf-8')

b't'

In [86]:
feature_labels = [
        "px",
        "py",
        "pz",
        "E",
        "E_rel",
        "pT",
        "pT_rel",
        "eta",
        "eta_rel",
        "eta_rot",
        "phi",
        "phi_rel",
        "phi_rot",
        "Delta_R",
        "cos(theta)",
        "cos(theta_rel)",
    ]

In [114]:
a = np.array([0,0,0,0])
print(a!=0)

[False False False False]


In [115]:
constituents_distribution = []
for jet in rand_data:
    const_nb = 0
    for const in jet:
        if const[0] != 0:
            const_nb += 1
    constituents_distribution.append(const_nb)

print(constituents_distribution)

[4, 4, 4, 4, 4]


In [6]:
np.arange(0,2,0.25)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75])

In [10]:
print(np.asarray(np.append(np.append(np.arange(0,2,0.25),np.arange(2,5,0.5)), np.arange(5,11,1))))

[ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.    2.5   3.    3.5
  4.    4.5   5.    6.    7.    8.    9.   10.  ]


In [7]:
import sys
import time

In [17]:
print('Starting process')

sys.stdout.write('\r')
# the exact output you're looking for:
sys.stdout.write("[%-20s] %d%%" % ('='*1, 5*1))
sys.stdout.flush()
time.sleep(0.5)

for i in range(2, 21):
    sys.stdout.write('\r')
    # the exact output you're looking for:
    sys.stdout.write("[%-20s] %d%%" % ('='*i, 5*i))
    sys.stdout.flush()
    time.sleep(0.5)

print('\nProcess complete')
    

Starting process
[====================] 100%
Process complete


In [15]:
a = 12
b= 'fish'

print(f'Hello {a}{b}')

Hello 12fish


In [72]:
a = np.array([[1]])
for i in range(4):
    a = np.concatenate((a,[[i]]), axis = 0)

print(a)

[[1]
 [0]
 [1]
 [2]
 [3]]


In [75]:
b = np.array([[9]])

for i in range(2,6):
    b = np.concatenate((b,[[i]]), axis = 0)

print(b)

[[9]
 [2]
 [3]
 [4]
 [5]]


In [74]:
print(np.concatenate((a,b), axis = 1))

[[1 9]
 [0 2]
 [1 3]
 [2 4]
 [3 5]]


In [4]:
c = np.array([])

for i in range(4):
    c = np.append(c, i)

print(c)

d = np.array([])

for i in range(5,9):
    d = np.append(d, i)

print(d)

e = np.concatenate(([c],[d]), axis =0)
print(e)

[0. 1. 2. 3.]
[5. 6. 7. 8.]
[[0. 1. 2. 3.]
 [5. 6. 7. 8.]]


In [5]:
np.swapaxes(e, 0, 1)

array([[0., 5.],
       [1., 6.],
       [2., 7.],
       [3., 8.]])

In [7]:
e[:,1]

array([1., 6.])

In [36]:
def combine_array(a1, a2):
    if np.ndim(a1) == 2:
        combined_array = np.concatenate((a1, [a2]), axis = 0)
    elif np.ndim(a1) == 1:
        combined_array = np.concatenate(([a1], [a2]), axis =1)

    return combined_array

In [32]:
f = np.array([])

f = np.concatenate(([f], [c]), axis = 1)
print(np.asarray(f))

f = np.concatenate((f,[d]), axis = 0)

print(np.asarray(f))

[[0. 1. 2. 3.]]
[[0. 1. 2. 3.]
 [5. 6. 7. 8.]]


In [28]:
np.ndim(c)

1

In [38]:
f = np.array([])

f = combine_array(f, c)
print(f)

f = combine_array(f,d)
print(f)

[[0. 1. 2. 3.]]
[[0. 1. 2. 3.]
 [5. 6. 7. 8.]]


In [5]:
import os

def get_file_paths(data_file_dir: str) -> list:
    """Gets path to the data files inside a given directory.

    Args:
        data_file_dir: Path to directory containing the data files.

    Returns:
        Array of paths to the data files themselves.
    """
    file_names = os.listdir(data_file_dir)
    print(file_names)
    file_paths = [os.path.join(data_file_dir, file_name) for file_name in file_names]

    return file_paths

In [6]:
get_file_paths('../Data/train/')

['jetImage_0_150p_40000_50000.h5', 'jetImage_4_150p_20000_30000.h5', 'jetImage_2_150p_50000_60000.h5', 'jetImage_5_150p_30000_40000.h5', 'jetImage_0_150p_70000_80000.h5', 'jetImage_3_150p_20000_30000.h5', 'jetImage_1_150p_0_10000.h5', 'jetImage_5_150p_50000_60000.h5', 'jetImage_2_150p_30000_40000.h5', 'jetImage_0_150p_0_10000.h5', 'jetImage_1_150p_80000_90000.h5', 'jetImage_1_150p_10000_20000.h5', 'jetImage_0_150p_60000_70000.h5', 'jetImage_6_150p_10000_20000.h5', 'jetImage_6_150p_80000_90000.h5', 'jetImage_0_150p_20000_30000.h5', 'jetImage_3_150p_70000_80000.h5', 'jetImage_1_150p_30000_40000.h5', 'jetImage_6_150p_50000_60000.h5', 'jetImage_3_150p_0_10000.h5', 'jetImage_4_150p_70000_80000.h5', 'jetImage_6_150p_30000_40000.h5', 'jetImage_1_150p_50000_60000.h5', 'jetImage_4_150p_40000_50000.h5', 'jetImage_3_150p_40000_50000.h5', 'jetImage_3_150p_60000_70000.h5', 'jetImage_5_150p_80000_90000.h5', 'jetImage_5_150p_10000_20000.h5', 'jetImage_2_150p_0_10000.h5', 'jetImage_4_150p_60000_70000.

['../Data/train/jetImage_0_150p_40000_50000.h5',
 '../Data/train/jetImage_4_150p_20000_30000.h5',
 '../Data/train/jetImage_2_150p_50000_60000.h5',
 '../Data/train/jetImage_5_150p_30000_40000.h5',
 '../Data/train/jetImage_0_150p_70000_80000.h5',
 '../Data/train/jetImage_3_150p_20000_30000.h5',
 '../Data/train/jetImage_1_150p_0_10000.h5',
 '../Data/train/jetImage_5_150p_50000_60000.h5',
 '../Data/train/jetImage_2_150p_30000_40000.h5',
 '../Data/train/jetImage_0_150p_0_10000.h5',
 '../Data/train/jetImage_1_150p_80000_90000.h5',
 '../Data/train/jetImage_1_150p_10000_20000.h5',
 '../Data/train/jetImage_0_150p_60000_70000.h5',
 '../Data/train/jetImage_6_150p_10000_20000.h5',
 '../Data/train/jetImage_6_150p_80000_90000.h5',
 '../Data/train/jetImage_0_150p_20000_30000.h5',
 '../Data/train/jetImage_3_150p_70000_80000.h5',
 '../Data/train/jetImage_1_150p_30000_40000.h5',
 '../Data/train/jetImage_6_150p_50000_60000.h5',
 '../Data/train/jetImage_3_150p_0_10000.h5',
 '../Data/train/jetImage_4_150p_

In [12]:
1%5

1

In [13]:
5%5

0

In [14]:
9%5

4

In [16]:
print('\rtest', flush = True)
print('\rcheese', flush = True)

test
cheese


In [36]:
from terminal_colors import tcols

a = True
print(tcols.FAIL+f'I just came to say {a*"hello"+(not a)*"goodbye"}'+tcols.ENDC)

I just came to say hello


In [1]:
def rah(fam:str='cheese'):
    print(fam)

In [2]:
rah()

cheese


In [3]:
rah('geezer')

geezer


In [7]:
true_class = [[True],[False], [True]]
df = pd.DataFrame(data = true_class, columns = ['class'])

In [8]:
df

class
0   True
1  False
2   True

In [10]:
df['class'] * 1

0    1
1    0
2    1
Name: class, dtype: int64

In [11]:
true_class

[[True], [False], [True]]

In [21]:
other_class = [[False], [False], [True]]

In [22]:
print(true_class and other_class)

[[False], [False], [True]]


In [6]:
a = [[1,2,2,3,4,1],[5,4,6,1,2,2]]

In [44]:
np.pad(a, ((1,2), (3,4)), constant_values= ((-99,20),(12,-9)))

array([[ 12,  12,  12, -99, -99, -99, -99, -99, -99,  -9,  -9,  -9,  -9],
       [ 12,  12,  12,   1,   2,   2,   3,   4,   1,  -9,  -9,  -9,  -9],
       [ 12,  12,  12,   5,   4,   6,   1,   2,   2,  -9,  -9,  -9,  -9],
       [ 12,  12,  12,  20,  20,  20,  20,  20,  20,  -9,  -9,  -9,  -9],
       [ 12,  12,  12,  20,  20,  20,  20,  20,  20,  -9,  -9,  -9,  -9]])

In [1]:
b = [1,2,3,1,2,1]

In [15]:
import pandas as pd
df = pd.DataFrame(a, columns = ['a', 'b', 'c', 'd', 'e', 'f'])

In [18]:
df['new'] = [8,1]

In [19]:
df

a  b  c  d  e  f  new
0  1  2  2  3  4  1    8
1  5  4  6  1  2  2    1

In [25]:
import numpy as np
np.mean(b[:4])

1.75