In [1]:
import numpy as np
import pandas as pd

In [25]:
data = [[1.3,6.2,7.3,], [4.2,8.1,0.3], [3.7,1.1,2.8], [13.2,8.2,3.1,], [1.3,5.1,3.9], [3.2,4.1,12.5]]

heading = ['a', 'b', 'c']

ohe_data = np.array([[0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 0, 1],
 [0, 1, 0, 0, 0]])

classes = np.array([b'g', b'q', b'w', b'z', b't'])

In [59]:
new_data = np.array([1.3,6.2,7.3,4.2,8.1,43.5])
for i in range(len(classes)):
    classed_data = np.array([])
    
    print(i)
    boolean_mask = [np.argmax(y)==i for y in ohe_data]
    print(boolean_mask)
    print(new_data[[np.argmax(y)==i for y in ohe_data]])

0
[False, True, False, False, False, False]
[6.2]
1
[False, False, False, False, False, True]
[43.5]
2
[False, False, True, True, False, False]
[7.3 4.2]
3
[True, False, False, False, False, False]
[1.3]
4
[False, False, False, False, True, False]
[8.1]


In [30]:
y_class = [classes[np.argmax(i)] for i in ohe_data]

print(y_class)
print(type(y_class[0]))

In [27]:
df = pd.DataFrame(data = data, columns = heading)
print(df)

In [34]:
df['class'] = y_class

In [35]:
df

a    b     c class
0   1.3  6.2   7.3  b'z'
1   4.2  8.1   0.3  b'g'
2   3.7  1.1   2.8  b'w'
3  13.2  8.2   3.1  b'w'
4   1.3  5.1   3.9  b't'
5   3.2  4.1  12.5  b'q'

In [37]:
print(df.dtypes)

a        float64
b        float64
c        float64
class     object
dtype: object


In [42]:
df['class']==classes[4]

0    False
1    False
2    False
3    False
4     True
5    False
Name: class, dtype: bool

In [43]:
df.to_csv('newtest.csv', index=False)
df_reloaded = pd.read_csv('newtest.csv', nrows = None)
print(df_reloaded)

      a    b     c class
0   1.3  6.2   7.3  b'z'
1   4.2  8.1   0.3  b'g'
2   3.7  1.1   2.8  b'w'
3  13.2  8.2   3.1  b'w'
4   1.3  5.1   3.9  b't'
5   3.2  4.1  12.5  b'q'


In [44]:
df_reloaded['class']==classes[4]

0    False
1    False
2    False
3    False
4    False
5    False
Name: class, dtype: bool

In [52]:
df = pd.DataFrame(data = data, columns = heading)
df['class'] = y_class
print(df)

print('\n=====================\n')

positive_class = b't'

if positive_class is not None:
  df["class"] = df["class"] == positive_class

print(df)

      a    b     c class
0   1.3  6.2   7.3  b'z'
1   4.2  8.1   0.3  b'g'
2   3.7  1.1   2.8  b'w'
3  13.2  8.2   3.1  b'w'
4   1.3  5.1   3.9  b't'
5   3.2  4.1  12.5  b'q'


      a    b     c  class
0   1.3  6.2   7.3  False
1   4.2  8.1   0.3  False
2   3.7  1.1   2.8  False
3  13.2  8.2   3.1  False
4   1.3  5.1   3.9   True
5   3.2  4.1  12.5  False


In [55]:
df.to_csv('newtest.csv', index=False)

In [2]:
rand_data = np.random.rand(5,6,3)
#big_rand_data = np.random.rand(620000,50,16)
print(rand_data)

[[[0.97598521 0.46451769 0.68324875]
  [0.04530233 0.17196193 0.27966348]
  [0.93607227 0.12603521 0.59234387]
  [0.12328506 0.95324556 0.60434421]
  [0.73313066 0.01908425 0.63726337]
  [0.63894661 0.49833072 0.07363653]]

 [[0.84896181 0.39052693 0.89963051]
  [0.33282899 0.49854824 0.97841278]
  [0.30915256 0.07526956 0.43003704]
  [0.55062703 0.84353724 0.33842393]
  [0.58165641 0.00923529 0.50745167]
  [0.49532896 0.97089076 0.56013527]]

 [[0.00211385 0.3702846  0.29855901]
  [0.07609572 0.26658968 0.66000618]
  [0.72347958 0.93894056 0.11300049]
  [0.2159265  0.5226799  0.08534608]
  [0.32266798 0.31871192 0.8128471 ]
  [0.89629641 0.06436677 0.32116307]]

 [[0.52864047 0.77375429 0.53961519]
  [0.50785329 0.03543585 0.4174925 ]
  [0.43716491 0.63705165 0.7444652 ]
  [0.90554112 0.39975684 0.16924763]
  [0.89653021 0.03400744 0.78194112]
  [0.58648044 0.14747215 0.57118073]]

 [[0.89868098 0.93335465 0.07539908]
  [0.46328928 0.48838741 0.58216414]
  [0.79193718 0.78343598 0.537

In [3]:
ascending = False
order = ascending - (not ascending)
print(order)

-1


In [4]:
sorted_data = np.array([rand_data[i][(order*rand_data[i][:, 0]).argsort()] for i in range(len(rand_data))])
#big_sorted_data = np.asarray([big_rand_data[i][big_rand_data[i][:, 1].argsort()] for i in range(len(big_rand_data))])

print(sorted_data)
print(type(sorted_data))

[[[0.97598521 0.46451769 0.68324875]
  [0.93607227 0.12603521 0.59234387]
  [0.73313066 0.01908425 0.63726337]
  [0.63894661 0.49833072 0.07363653]
  [0.12328506 0.95324556 0.60434421]
  [0.04530233 0.17196193 0.27966348]]

 [[0.84896181 0.39052693 0.89963051]
  [0.58165641 0.00923529 0.50745167]
  [0.55062703 0.84353724 0.33842393]
  [0.49532896 0.97089076 0.56013527]
  [0.33282899 0.49854824 0.97841278]
  [0.30915256 0.07526956 0.43003704]]

 [[0.89629641 0.06436677 0.32116307]
  [0.72347958 0.93894056 0.11300049]
  [0.32266798 0.31871192 0.8128471 ]
  [0.2159265  0.5226799  0.08534608]
  [0.07609572 0.26658968 0.66000618]
  [0.00211385 0.3702846  0.29855901]]

 [[0.90554112 0.39975684 0.16924763]
  [0.89653021 0.03400744 0.78194112]
  [0.58648044 0.14747215 0.57118073]
  [0.52864047 0.77375429 0.53961519]
  [0.50785329 0.03543585 0.4174925 ]
  [0.43716491 0.63705165 0.7444652 ]]

 [[0.98371109 0.81191408 0.16375969]
  [0.89868098 0.93335465 0.07539908]
  [0.79193718 0.78343598 0.537

In [5]:
boolean_index = [True, False, False, True, False]

print(sorted_data[:,:,1][boolean_index].flatten())

[0.46451769 0.12603521 0.01908425 0.49833072 0.95324556 0.17196193
 0.39975684 0.03400744 0.14747215 0.77375429 0.03543585 0.63705165]


In [6]:
print(boolean_index)
print(1*(boolean_index))

[True, False, False, True, False]
[True, False, False, True, False]


In [7]:
boolean_mask = sorted_data[:, :, 0] > 0.2
structure_memory = boolean_mask.sum(axis=1)

In [8]:
print(boolean_mask)
print(structure_memory)
print(np.mean(structure_memory))

[[ True  True  True  True False False]
 [ True  True  True  True  True  True]
 [ True  True  True  True False False]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
[4 6 4 6 6]
5.2


In [9]:
cut_data = np.split(sorted_data[boolean_mask, :], np.cumsum(structure_memory)[:-1])

print(cut_data)
print('\n================\n')
cut_data = [jet_const for jet_const in cut_data if jet_const.size > 0]

print(cut_data)

[array([[0.97598521, 0.46451769, 0.68324875],
       [0.93607227, 0.12603521, 0.59234387],
       [0.73313066, 0.01908425, 0.63726337],
       [0.63894661, 0.49833072, 0.07363653]]), array([[0.84896181, 0.39052693, 0.89963051],
       [0.58165641, 0.00923529, 0.50745167],
       [0.55062703, 0.84353724, 0.33842393],
       [0.49532896, 0.97089076, 0.56013527],
       [0.33282899, 0.49854824, 0.97841278],
       [0.30915256, 0.07526956, 0.43003704]]), array([[0.89629641, 0.06436677, 0.32116307],
       [0.72347958, 0.93894056, 0.11300049],
       [0.32266798, 0.31871192, 0.8128471 ],
       [0.2159265 , 0.5226799 , 0.08534608]]), array([[0.90554112, 0.39975684, 0.16924763],
       [0.89653021, 0.03400744, 0.78194112],
       [0.58648044, 0.14747215, 0.57118073],
       [0.52864047, 0.77375429, 0.53961519],
       [0.50785329, 0.03543585, 0.4174925 ],
       [0.43716491, 0.63705165, 0.7444652 ]]), array([[0.98371109, 0.81191408, 0.16375969],
       [0.89868098, 0.93335465, 0.07539908],
 

In [10]:
max_constituents = 6
nb_constituents = np.array([])

for jet in range(len(cut_data)):
    if cut_data[jet].shape[0] >= max_constituents:
        nb_constituents = np.append(nb_constituents, max_constituents)
        cut_data[jet] = cut_data[jet][:max_constituents, :]
    else:
        nb_constituents = np.append(nb_constituents, cut_data[jet].shape[0])
        padding_length = max_constituents - cut_data[jet].shape[0]
        cut_data[jet] = np.pad(cut_data[jet], ((0, padding_length), (0, 0)), constant_values = 0)
cut_data = np.array(cut_data)
print(cut_data)
print('\n===================\n')
print(nb_constituents)

[[[0.97598521 0.46451769 0.68324875]
  [0.93607227 0.12603521 0.59234387]
  [0.73313066 0.01908425 0.63726337]
  [0.63894661 0.49833072 0.07363653]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 [[0.84896181 0.39052693 0.89963051]
  [0.58165641 0.00923529 0.50745167]
  [0.55062703 0.84353724 0.33842393]
  [0.49532896 0.97089076 0.56013527]
  [0.33282899 0.49854824 0.97841278]
  [0.30915256 0.07526956 0.43003704]]

 [[0.89629641 0.06436677 0.32116307]
  [0.72347958 0.93894056 0.11300049]
  [0.32266798 0.31871192 0.8128471 ]
  [0.2159265  0.5226799  0.08534608]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 [[0.90554112 0.39975684 0.16924763]
  [0.89653021 0.03400744 0.78194112]
  [0.58648044 0.14747215 0.57118073]
  [0.52864047 0.77375429 0.53961519]
  [0.50785329 0.03543585 0.4174925 ]
  [0.43716491 0.63705165 0.7444652 ]]

 [[0.98371109 0.81191408 0.16375969]
  [0.89868098 0.93335465 0.07539908]
  [0.79193718 0.78343598 0.537

In [12]:
is_not_padded = np.any(cut_data, axis = 2)
print(is_not_padded)
# is_positive_class = [True, False, False, True, False]
# print(is_positive_class)

[[ True  True  True  True False False]
 [ True  True  True  True  True  True]
 [ True  True  True  True False False]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]


In [13]:
cut_boolean_mask = cut_data[:, :, 1] < 0.5
print(cut_boolean_mask)

[[ True  True  True  True  True  True]
 [ True  True False False  True  True]
 [ True False  True False  True  True]
 [ True  True  True False  True False]
 [False False False False  True  True]]


In [14]:
new_boolean_mask = cut_boolean_mask * is_not_padded
new_structure_memory = new_boolean_mask.sum(axis = 1)
print(new_boolean_mask)
print(new_structure_memory)

[[ True  True  True  True False False]
 [ True  True False False  True  True]
 [ True False  True False False False]
 [ True  True  True False  True False]
 [False False False False  True  True]]
[4 4 2 4 2]


In [15]:
new_cut_data = np.split(cut_data[new_boolean_mask, :], np.cumsum(new_structure_memory)[:-1])
print(new_cut_data)

# new_cut_data = [jet_const for jet_const in new_cut_data if jet_const.size >0]
# print(new_cut_data)

ascending = True
order = ascending - (not ascending)

new_cut_data = [new_cut_data[i][(order*new_cut_data[i][:, 1]).argsort()] for i in range(len(new_cut_data))]

print('-----------------')
print(new_cut_data)
print(type(new_cut_data))

[array([[0.97598521, 0.46451769, 0.68324875],
       [0.93607227, 0.12603521, 0.59234387],
       [0.73313066, 0.01908425, 0.63726337],
       [0.63894661, 0.49833072, 0.07363653]]), array([[0.84896181, 0.39052693, 0.89963051],
       [0.58165641, 0.00923529, 0.50745167],
       [0.33282899, 0.49854824, 0.97841278],
       [0.30915256, 0.07526956, 0.43003704]]), array([[0.89629641, 0.06436677, 0.32116307],
       [0.32266798, 0.31871192, 0.8128471 ]]), array([[0.90554112, 0.39975684, 0.16924763],
       [0.89653021, 0.03400744, 0.78194112],
       [0.58648044, 0.14747215, 0.57118073],
       [0.50785329, 0.03543585, 0.4174925 ]]), array([[0.46328928, 0.48838741, 0.58216414],
       [0.3554859 , 0.28393827, 0.0254519 ]])]
-----------------
[array([[0.73313066, 0.01908425, 0.63726337],
       [0.93607227, 0.12603521, 0.59234387],
       [0.97598521, 0.46451769, 0.68324875],
       [0.63894661, 0.49833072, 0.07363653]]), array([[0.58165641, 0.00923529, 0.50745167],
       [0.30915256, 0.0

In [41]:
means = [np.mean(jet_const[:3,2]) for jet_const in new_cut_data]
sums = [np.sum(jet_const[:4,0]) for jet_const in new_cut_data]
print(means)
print(sums)
print(type(means))

[0.6376186663225737, 0.6123730745927367, 0.5670050829190735, 0.5902047839454125, 0.30380801868786506]
[3.2841347463091703, 2.0725997716904647, 1.2189643925900306, 2.8964050535160792, 0.8187751855245107]
<class 'list'>


In [69]:
feature_labels  = ['a','b','c']

def create_aggregated_feature(x_data, operation, feature, nb_const, sorted_feature='b', sort_ascending=True):
    try:
        sorted_feature_index = feature_labels.index(sorted_feature)
    except:
        print(f"'{sorted_feature}' not found in list of features!")
        return

    order = sort_ascending - (not sort_ascending)

    sorted_data = [x_data[i][(order*x_data[i][:, sorted_feature_index]).argsort()] for i in range(len(x_data))]
    
    try:
        feature_index = feature_labels.index(feature)
    except:
        print(f"'{feature}' not found in list of features!")
        return
    
    switcher = {
        "mean": lambda: [np.mean(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
        "median": lambda: [np.median(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
        "min": lambda: [np.amin(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
        "max": lambda: [np.amax(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
        "sum": lambda: [np.sum(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
    }

    aggregated_feature = switcher.get(operation, lambda: None)()
    if aggregated_feature is None:
        raise TypeError(f"'{operation}' not found from list of operations!")
    
    return aggregated_feature
    

In [70]:
alt_means_ = create_aggregated_feature_(new_cut_data, 'max', 'c', 3, sorted_feature='a', sort_ascending = True)
print(alt_means_)
alt_sums_ = create_aggregated_feature_(new_cut_data, 'median', 'a', 4)
print(alt_sums_)

break_test = create_aggregated_feature_(new_cut_data, 'me', 'd', 2)

[0.6372633725452542, 0.978412780433305, 0.8128470964541042, 0.7819411222973951, 0.5821641355727636]
[0.8346014629047572, 0.45724270350041957, 0.6094821962950153, 0.7415053243592926, 0.40938759276225534]
'd' not found in list of features!


In [110]:
max_constituents = 4
new_nb_constituents = np.array([])

for jet in range(len(new_cut_data)):
    if new_cut_data[jet].shape[0] >= max_constituents:
        new_nb_constituents = np.append(new_nb_constituents, max_constituents)
        new_cut_data[jet] = new_cut_data[jet][:max_constituents, :]
    else:
        new_nb_constituents = np.append(new_nb_constituents, new_cut_data[jet].shape[0])
        padding_length = max_constituents - new_cut_data[jet].shape[0]
        new_cut_data[jet] = np.pad(new_cut_data[jet], ((0, padding_length), (0, 0)), constant_values = -0.999)
new_cut_data = np.array(new_cut_data)
print(new_cut_data)
print('\n===================\n')
print(new_nb_constituents)

[[[ 0.62329008  0.31537603  0.98695186]
  [ 0.2092492   0.37123428  0.07122857]
  [-0.999      -0.999      -0.999     ]
  [-0.999      -0.999      -0.999     ]]

 [[ 0.61153328  0.30160817  0.08293803]
  [-0.999      -0.999      -0.999     ]
  [-0.999      -0.999      -0.999     ]
  [-0.999      -0.999      -0.999     ]]

 [[ 0.20614618  0.23781982  0.07321044]
  [ 0.29814028  0.3613127   0.68847572]
  [ 0.75464347  0.48001996  0.3304572 ]
  [-0.999      -0.999      -0.999     ]]

 [[ 0.23920947  0.05308377  0.38631762]
  [ 0.21820527  0.16563036  0.03788958]
  [ 0.31354992  0.16757342  0.09224389]
  [ 0.96516806  0.19341745  0.0067916 ]]

 [[ 0.60452188  0.16031759  0.39418248]
  [ 0.50079443  0.25102322  0.03547827]
  [ 0.22961632  0.37072405  0.34178145]
  [-0.999      -0.999      -0.999     ]]]


[2. 1. 3. 4. 3.]


In [71]:
positive_class = 't'

In [85]:
bytes(positive_class, 'utf-8')

b't'

In [86]:
feature_labels = [
        "px",
        "py",
        "pz",
        "E",
        "E_rel",
        "pT",
        "pT_rel",
        "eta",
        "eta_rel",
        "eta_rot",
        "phi",
        "phi_rel",
        "phi_rot",
        "Delta_R",
        "cos(theta)",
        "cos(theta_rel)",
    ]

In [114]:
a = np.array([0,0,0,0])
print(a!=0)

[False False False False]


In [115]:
constituents_distribution = []
for jet in rand_data:
    const_nb = 0
    for const in jet:
        if const[0] != 0:
            const_nb += 1
    constituents_distribution.append(const_nb)

print(constituents_distribution)

[4, 4, 4, 4, 4]


In [6]:
np.arange(0,2,0.25)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75])

In [10]:
print(np.asarray(np.append(np.append(np.arange(0,2,0.25),np.arange(2,5,0.5)), np.arange(5,11,1))))

[ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.    2.5   3.    3.5
  4.    4.5   5.    6.    7.    8.    9.   10.  ]


In [7]:
import sys
import time

In [17]:
print('Starting process')

sys.stdout.write('\r')
# the exact output you're looking for:
sys.stdout.write("[%-20s] %d%%" % ('='*1, 5*1))
sys.stdout.flush()
time.sleep(0.5)

for i in range(2, 21):
    sys.stdout.write('\r')
    # the exact output you're looking for:
    sys.stdout.write("[%-20s] %d%%" % ('='*i, 5*i))
    sys.stdout.flush()
    time.sleep(0.5)

print('\nProcess complete')
    

Starting process
[====================] 100%
Process complete


In [15]:
a = 12
b= 'fish'

print(f'Hello {a}{b}')

Hello 12fish


In [72]:
a = np.array([[1]])
for i in range(4):
    a = np.concatenate((a,[[i]]), axis = 0)

print(a)

[[1]
 [0]
 [1]
 [2]
 [3]]


In [75]:
b = np.array([[9]])

for i in range(2,6):
    b = np.concatenate((b,[[i]]), axis = 0)

print(b)

[[9]
 [2]
 [3]
 [4]
 [5]]


In [74]:
print(np.concatenate((a,b), axis = 1))

[[1 9]
 [0 2]
 [1 3]
 [2 4]
 [3 5]]


In [4]:
c = np.array([])

for i in range(4):
    c = np.append(c, i)

print(c)

d = np.array([])

for i in range(5,9):
    d = np.append(d, i)

print(d)

e = np.concatenate(([c],[d]), axis =0)
print(e)

[0. 1. 2. 3.]
[5. 6. 7. 8.]
[[0. 1. 2. 3.]
 [5. 6. 7. 8.]]


In [5]:
np.swapaxes(e, 0, 1)

array([[0., 5.],
       [1., 6.],
       [2., 7.],
       [3., 8.]])

In [7]:
e[:,1]

array([1., 6.])

In [36]:
def combine_array(a1, a2):
    if np.ndim(a1) == 2:
        combined_array = np.concatenate((a1, [a2]), axis = 0)
    elif np.ndim(a1) == 1:
        combined_array = np.concatenate(([a1], [a2]), axis =1)

    return combined_array

In [32]:
f = np.array([])

f = np.concatenate(([f], [c]), axis = 1)
print(np.asarray(f))

f = np.concatenate((f,[d]), axis = 0)

print(np.asarray(f))

[[0. 1. 2. 3.]]
[[0. 1. 2. 3.]
 [5. 6. 7. 8.]]


In [28]:
np.ndim(c)

1

In [38]:
f = np.array([])

f = combine_array(f, c)
print(f)

f = combine_array(f,d)
print(f)

[[0. 1. 2. 3.]]
[[0. 1. 2. 3.]
 [5. 6. 7. 8.]]


In [5]:
import os

def get_file_paths(data_file_dir: str) -> list:
    """Gets path to the data files inside a given directory.

    Args:
        data_file_dir: Path to directory containing the data files.

    Returns:
        Array of paths to the data files themselves.
    """
    file_names = os.listdir(data_file_dir)
    print(file_names)
    file_paths = [os.path.join(data_file_dir, file_name) for file_name in file_names]

    return file_paths

In [6]:
get_file_paths('../Data/train/')

['jetImage_0_150p_40000_50000.h5', 'jetImage_4_150p_20000_30000.h5', 'jetImage_2_150p_50000_60000.h5', 'jetImage_5_150p_30000_40000.h5', 'jetImage_0_150p_70000_80000.h5', 'jetImage_3_150p_20000_30000.h5', 'jetImage_1_150p_0_10000.h5', 'jetImage_5_150p_50000_60000.h5', 'jetImage_2_150p_30000_40000.h5', 'jetImage_0_150p_0_10000.h5', 'jetImage_1_150p_80000_90000.h5', 'jetImage_1_150p_10000_20000.h5', 'jetImage_0_150p_60000_70000.h5', 'jetImage_6_150p_10000_20000.h5', 'jetImage_6_150p_80000_90000.h5', 'jetImage_0_150p_20000_30000.h5', 'jetImage_3_150p_70000_80000.h5', 'jetImage_1_150p_30000_40000.h5', 'jetImage_6_150p_50000_60000.h5', 'jetImage_3_150p_0_10000.h5', 'jetImage_4_150p_70000_80000.h5', 'jetImage_6_150p_30000_40000.h5', 'jetImage_1_150p_50000_60000.h5', 'jetImage_4_150p_40000_50000.h5', 'jetImage_3_150p_40000_50000.h5', 'jetImage_3_150p_60000_70000.h5', 'jetImage_5_150p_80000_90000.h5', 'jetImage_5_150p_10000_20000.h5', 'jetImage_2_150p_0_10000.h5', 'jetImage_4_150p_60000_70000.

['../Data/train/jetImage_0_150p_40000_50000.h5',
 '../Data/train/jetImage_4_150p_20000_30000.h5',
 '../Data/train/jetImage_2_150p_50000_60000.h5',
 '../Data/train/jetImage_5_150p_30000_40000.h5',
 '../Data/train/jetImage_0_150p_70000_80000.h5',
 '../Data/train/jetImage_3_150p_20000_30000.h5',
 '../Data/train/jetImage_1_150p_0_10000.h5',
 '../Data/train/jetImage_5_150p_50000_60000.h5',
 '../Data/train/jetImage_2_150p_30000_40000.h5',
 '../Data/train/jetImage_0_150p_0_10000.h5',
 '../Data/train/jetImage_1_150p_80000_90000.h5',
 '../Data/train/jetImage_1_150p_10000_20000.h5',
 '../Data/train/jetImage_0_150p_60000_70000.h5',
 '../Data/train/jetImage_6_150p_10000_20000.h5',
 '../Data/train/jetImage_6_150p_80000_90000.h5',
 '../Data/train/jetImage_0_150p_20000_30000.h5',
 '../Data/train/jetImage_3_150p_70000_80000.h5',
 '../Data/train/jetImage_1_150p_30000_40000.h5',
 '../Data/train/jetImage_6_150p_50000_60000.h5',
 '../Data/train/jetImage_3_150p_0_10000.h5',
 '../Data/train/jetImage_4_150p_

In [12]:
1%5

1

In [13]:
5%5

0

In [14]:
9%5

4

In [16]:
print('\rtest', flush = True)
print('\rcheese', flush = True)

test
cheese


In [36]:
from terminal_colors import tcols

a = True
print(tcols.FAIL+f'I just came to say {a*"hello"+(not a)*"goodbye"}'+tcols.ENDC)

I just came to say hello


In [1]:
def rah(fam:str='cheese'):
    print(fam)

In [2]:
rah()

cheese


In [3]:
rah('geezer')

geezer


In [7]:
true_class = [[True],[False], [True]]
df = pd.DataFrame(data = true_class, columns = ['class'])

In [8]:
df

class
0   True
1  False
2   True

In [10]:
df['class'] * 1

0    1
1    0
2    1
Name: class, dtype: int64

In [11]:
true_class

[[True], [False], [True]]

In [21]:
other_class = [[False], [False], [True]]

In [22]:
print(true_class and other_class)

[[False], [False], [True]]


In [6]:
a = [[1,2,2,3,4,1],[5,4,6,1,2,2]]

In [44]:
np.pad(a, ((1,2), (3,4)), constant_values= ((-99,20),(12,-9)))

array([[ 12,  12,  12, -99, -99, -99, -99, -99, -99,  -9,  -9,  -9,  -9],
       [ 12,  12,  12,   1,   2,   2,   3,   4,   1,  -9,  -9,  -9,  -9],
       [ 12,  12,  12,   5,   4,   6,   1,   2,   2,  -9,  -9,  -9,  -9],
       [ 12,  12,  12,  20,  20,  20,  20,  20,  20,  -9,  -9,  -9,  -9],
       [ 12,  12,  12,  20,  20,  20,  20,  20,  20,  -9,  -9,  -9,  -9]])

In [1]:
b = [1,2,3,1,2,1]

In [15]:
import pandas as pd
df = pd.DataFrame(a, columns = ['a', 'b', 'c', 'd', 'e', 'f'])

In [18]:
df['new'] = [8,1]

In [19]:
df

a  b  c  d  e  f  new
0  1  2  2  3  4  1    8
1  5  4  6  1  2  2    1

In [25]:
import numpy as np
np.mean(b[:4])

1.75