In [1]:
import numpy as np
import pandas as pd

In [25]:
data = [[1.3,6.2,7.3,], [4.2,8.1,0.3], [3.7,1.1,2.8], [13.2,8.2,3.1,], [1.3,5.1,3.9], [3.2,4.1,12.5]]

heading = ['a', 'b', 'c']

ohe_data = np.array([[0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 0, 1],
 [0, 1, 0, 0, 0]])

classes = np.array([b'g', b'q', b'w', b'z', b't'])

In [59]:
new_data = np.array([1.3,6.2,7.3,4.2,8.1,43.5])
for i in range(len(classes)):
    classed_data = np.array([])
    
    print(i)
    boolean_mask = [np.argmax(y)==i for y in ohe_data]
    print(boolean_mask)
    print(new_data[[np.argmax(y)==i for y in ohe_data]])

0
[False, True, False, False, False, False]
[6.2]
1
[False, False, False, False, False, True]
[43.5]
2
[False, False, True, True, False, False]
[7.3 4.2]
3
[True, False, False, False, False, False]
[1.3]
4
[False, False, False, False, True, False]
[8.1]


In [30]:
y_class = [classes[np.argmax(i)] for i in ohe_data]

print(y_class)
print(type(y_class[0]))

In [27]:
df = pd.DataFrame(data = data, columns = heading)
print(df)

In [34]:
df['class'] = y_class

In [35]:
df

a    b     c class
0   1.3  6.2   7.3  b'z'
1   4.2  8.1   0.3  b'g'
2   3.7  1.1   2.8  b'w'
3  13.2  8.2   3.1  b'w'
4   1.3  5.1   3.9  b't'
5   3.2  4.1  12.5  b'q'

In [37]:
print(df.dtypes)

a        float64
b        float64
c        float64
class     object
dtype: object


In [42]:
df['class']==classes[4]

0    False
1    False
2    False
3    False
4     True
5    False
Name: class, dtype: bool

In [43]:
df.to_csv('newtest.csv', index=False)
df_reloaded = pd.read_csv('newtest.csv', nrows = None)
print(df_reloaded)

      a    b     c class
0   1.3  6.2   7.3  b'z'
1   4.2  8.1   0.3  b'g'
2   3.7  1.1   2.8  b'w'
3  13.2  8.2   3.1  b'w'
4   1.3  5.1   3.9  b't'
5   3.2  4.1  12.5  b'q'


In [44]:
df_reloaded['class']==classes[4]

0    False
1    False
2    False
3    False
4    False
5    False
Name: class, dtype: bool

In [52]:
df = pd.DataFrame(data = data, columns = heading)
df['class'] = y_class
print(df)

print('\n=====================\n')

positive_class = b't'

if positive_class is not None:
  df["class"] = df["class"] == positive_class

print(df)

      a    b     c class
0   1.3  6.2   7.3  b'z'
1   4.2  8.1   0.3  b'g'
2   3.7  1.1   2.8  b'w'
3  13.2  8.2   3.1  b'w'
4   1.3  5.1   3.9  b't'
5   3.2  4.1  12.5  b'q'


      a    b     c  class
0   1.3  6.2   7.3  False
1   4.2  8.1   0.3  False
2   3.7  1.1   2.8  False
3  13.2  8.2   3.1  False
4   1.3  5.1   3.9   True
5   3.2  4.1  12.5  False


In [55]:
df.to_csv('newtest.csv', index=False)

In [12]:
rand_data = np.random.rand(5,6,3)
#big_rand_data = np.random.rand(620000,50,16)
print(rand_data)

[[[0.09915398 0.25271707 0.84350915]
  [0.55164128 0.62986962 0.94927525]
  [0.63655692 0.20080617 0.18718767]
  [0.94240982 0.85684497 0.88913425]
  [0.97871777 0.00493207 0.12839267]
  [0.91614239 0.43950862 0.93022106]]

 [[0.07350698 0.18439888 0.22193239]
  [0.44960439 0.43133851 0.99806502]
  [0.14887639 0.20596089 0.62355619]
  [0.16844943 0.07062142 0.46866591]
  [0.62572271 0.99818351 0.08608671]
  [0.75911078 0.15526972 0.86311801]]

 [[0.20231241 0.16898222 0.09879337]
  [0.22587164 0.7093602  0.16544768]
  [0.02821424 0.4242962  0.49214306]
  [0.77812389 0.98522281 0.75399566]
  [0.59754777 0.34021658 0.85162951]
  [0.16175673 0.24076111 0.94967263]]

 [[0.74083859 0.26360265 0.81657987]
  [0.99859102 0.48974848 0.65894335]
  [0.60409017 0.41683892 0.94826283]
  [0.26113121 0.05058671 0.80351888]
  [0.00496414 0.00898791 0.84591535]
  [0.283656   0.88065357 0.88878192]]

 [[0.69501631 0.19890341 0.55740391]
  [0.21209679 0.10519732 0.69824999]
  [0.24753559 0.44774405 0.934

In [13]:
ascending = False
order = ascending - (not ascending)
print(order)

-1


In [14]:
sorted_data = np.array([rand_data[i][(order*rand_data[i][:, 0]).argsort()] for i in range(len(rand_data))])
#big_sorted_data = np.asarray([big_rand_data[i][big_rand_data[i][:, 1].argsort()] for i in range(len(big_rand_data))])

print(sorted_data)
print(type(sorted_data))

[[[0.97871777 0.00493207 0.12839267]
  [0.94240982 0.85684497 0.88913425]
  [0.91614239 0.43950862 0.93022106]
  [0.63655692 0.20080617 0.18718767]
  [0.55164128 0.62986962 0.94927525]
  [0.09915398 0.25271707 0.84350915]]

 [[0.75911078 0.15526972 0.86311801]
  [0.62572271 0.99818351 0.08608671]
  [0.44960439 0.43133851 0.99806502]
  [0.16844943 0.07062142 0.46866591]
  [0.14887639 0.20596089 0.62355619]
  [0.07350698 0.18439888 0.22193239]]

 [[0.77812389 0.98522281 0.75399566]
  [0.59754777 0.34021658 0.85162951]
  [0.22587164 0.7093602  0.16544768]
  [0.20231241 0.16898222 0.09879337]
  [0.16175673 0.24076111 0.94967263]
  [0.02821424 0.4242962  0.49214306]]

 [[0.99859102 0.48974848 0.65894335]
  [0.74083859 0.26360265 0.81657987]
  [0.60409017 0.41683892 0.94826283]
  [0.283656   0.88065357 0.88878192]
  [0.26113121 0.05058671 0.80351888]
  [0.00496414 0.00898791 0.84591535]]

 [[0.69501631 0.19890341 0.55740391]
  [0.2495631  0.89155663 0.30321663]
  [0.24753559 0.44774405 0.934

In [15]:
boolean_index = [True, False, False, True, False]

print(sorted_data[:,:,1][boolean_index].flatten())

[0.00493207 0.85684497 0.43950862 0.20080617 0.62986962 0.25271707
 0.48974848 0.26360265 0.41683892 0.88065357 0.05058671 0.00898791]


In [16]:
print(boolean_index)
print(1*(boolean_index))

[True, False, False, True, False]
[True, False, False, True, False]


In [17]:
boolean_mask = sorted_data[:, :, 0] > 0.2
structure_memory = boolean_mask.sum(axis=1)

In [18]:
print(boolean_mask)
print(structure_memory)
print(np.mean(structure_memory))

[[ True  True  True  True  True False]
 [ True  True  True False False False]
 [ True  True  True  True False False]
 [ True  True  True  True  True False]
 [ True  True  True  True False False]]
[5 3 4 5 4]
4.2


In [19]:
cut_data = np.split(sorted_data[boolean_mask, :], np.cumsum(structure_memory)[:-1])

print(cut_data)
print('\n================\n')
cut_data = [jet_const for jet_const in cut_data if jet_const.size > 0]

print(cut_data)

[array([[0.97871777, 0.00493207, 0.12839267],
       [0.94240982, 0.85684497, 0.88913425],
       [0.91614239, 0.43950862, 0.93022106],
       [0.63655692, 0.20080617, 0.18718767],
       [0.55164128, 0.62986962, 0.94927525]]), array([[0.75911078, 0.15526972, 0.86311801],
       [0.62572271, 0.99818351, 0.08608671],
       [0.44960439, 0.43133851, 0.99806502]]), array([[0.77812389, 0.98522281, 0.75399566],
       [0.59754777, 0.34021658, 0.85162951],
       [0.22587164, 0.7093602 , 0.16544768],
       [0.20231241, 0.16898222, 0.09879337]]), array([[0.99859102, 0.48974848, 0.65894335],
       [0.74083859, 0.26360265, 0.81657987],
       [0.60409017, 0.41683892, 0.94826283],
       [0.283656  , 0.88065357, 0.88878192],
       [0.26113121, 0.05058671, 0.80351888]]), array([[0.69501631, 0.19890341, 0.55740391],
       [0.2495631 , 0.89155663, 0.30321663],
       [0.24753559, 0.44774405, 0.93463885],
       [0.21209679, 0.10519732, 0.69824999]])]


[array([[0.97871777, 0.00493207, 0.1283926

In [20]:
max_constituents = 6
nb_constituents = np.array([])

for jet in range(len(cut_data)):
    if cut_data[jet].shape[0] >= max_constituents:
        nb_constituents = np.append(nb_constituents, max_constituents)
        cut_data[jet] = cut_data[jet][:max_constituents, :]
    else:
        nb_constituents = np.append(nb_constituents, cut_data[jet].shape[0])
        padding_length = max_constituents - cut_data[jet].shape[0]
        cut_data[jet] = np.pad(cut_data[jet], ((0, padding_length), (0, 0)), constant_values = 0)
cut_data = np.array(cut_data)
print(cut_data)
print('\n===================\n')
print(nb_constituents)

[[[0.97871777 0.00493207 0.12839267]
  [0.94240982 0.85684497 0.88913425]
  [0.91614239 0.43950862 0.93022106]
  [0.63655692 0.20080617 0.18718767]
  [0.55164128 0.62986962 0.94927525]
  [0.         0.         0.        ]]

 [[0.75911078 0.15526972 0.86311801]
  [0.62572271 0.99818351 0.08608671]
  [0.44960439 0.43133851 0.99806502]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 [[0.77812389 0.98522281 0.75399566]
  [0.59754777 0.34021658 0.85162951]
  [0.22587164 0.7093602  0.16544768]
  [0.20231241 0.16898222 0.09879337]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 [[0.99859102 0.48974848 0.65894335]
  [0.74083859 0.26360265 0.81657987]
  [0.60409017 0.41683892 0.94826283]
  [0.283656   0.88065357 0.88878192]
  [0.26113121 0.05058671 0.80351888]
  [0.         0.         0.        ]]

 [[0.69501631 0.19890341 0.55740391]
  [0.2495631  0.89155663 0.30321663]
  [0.24753559 0.44774405 0.934

In [21]:
is_not_padded = np.any(cut_data, axis = 2)
print(is_not_padded)
# is_positive_class = [True, False, False, True, False]
# print(is_positive_class)

[[ True  True  True  True  True False]
 [ True  True  True False False False]
 [ True  True  True  True False False]
 [ True  True  True  True  True False]
 [ True  True  True  True False False]]


In [22]:
cut_boolean_mask = cut_data[:, :, 1] < 0.5
print(cut_boolean_mask)

[[ True False  True  True False  True]
 [ True False  True  True  True  True]
 [False  True False  True  True  True]
 [ True  True  True False  True  True]
 [ True False  True  True  True  True]]


In [23]:
new_boolean_mask = cut_boolean_mask * is_not_padded
new_structure_memory = new_boolean_mask.sum(axis = 1)
print(new_boolean_mask)
print(new_structure_memory)

[[ True False  True  True False False]
 [ True False  True False False False]
 [False  True False  True False False]
 [ True  True  True False  True False]
 [ True False  True  True False False]]
[3 2 2 4 3]


In [24]:
new_cut_data = np.split(cut_data[new_boolean_mask, :], np.cumsum(new_structure_memory)[:-1])
print(new_cut_data)

# new_cut_data = [jet_const for jet_const in new_cut_data if jet_const.size >0]
# print(new_cut_data)

ascending = True
order = ascending - (not ascending)

new_cut_data = [new_cut_data[i][(order*new_cut_data[i][:, 1]).argsort()] for i in range(len(new_cut_data))]

print('-----------------')
print(new_cut_data)
print(type(new_cut_data))

[array([[0.97871777, 0.00493207, 0.12839267],
       [0.91614239, 0.43950862, 0.93022106],
       [0.63655692, 0.20080617, 0.18718767]]), array([[0.75911078, 0.15526972, 0.86311801],
       [0.44960439, 0.43133851, 0.99806502]]), array([[0.59754777, 0.34021658, 0.85162951],
       [0.20231241, 0.16898222, 0.09879337]]), array([[0.99859102, 0.48974848, 0.65894335],
       [0.74083859, 0.26360265, 0.81657987],
       [0.60409017, 0.41683892, 0.94826283],
       [0.26113121, 0.05058671, 0.80351888]]), array([[0.69501631, 0.19890341, 0.55740391],
       [0.24753559, 0.44774405, 0.93463885],
       [0.21209679, 0.10519732, 0.69824999]])]
-----------------
[array([[0.97871777, 0.00493207, 0.12839267],
       [0.63655692, 0.20080617, 0.18718767],
       [0.91614239, 0.43950862, 0.93022106]]), array([[0.75911078, 0.15526972, 0.86311801],
       [0.44960439, 0.43133851, 0.99806502]]), array([[0.20231241, 0.16898222, 0.09879337],
       [0.59754777, 0.34021658, 0.85162951]]), array([[0.26113121,

In [47]:
for jet_const in new_cut_data:
    print(jet_const[:,0])
    print(jet_const[:-1,0])

[0.97871777 0.63655692 0.91614239]
[0.97871777 0.63655692]
[0.75911078 0.44960439]
[0.75911078]
[0.20231241 0.59754777]
[0.20231241]
[0.26113121 0.74083859 0.60409017 0.99859102]
[0.26113121 0.74083859 0.60409017]
[0.21209679 0.69501631 0.24753559]
[0.21209679 0.69501631]


In [46]:
means_a = [np.mean(jet_const[:,0]) for jet_const in new_cut_data]
means_b = [np.mean(jet_const[:,1]) for jet_const in new_cut_data]
means_c = [np.mean(jet_const[:,2]) for jet_const in new_cut_data]
means_a_ = [np.mean(jet_const[:-1,0]) for jet_const in new_cut_data]
means_b_ = [np.mean(jet_const[:-1,1]) for jet_const in new_cut_data]
means_c_ = [np.mean(jet_const[:-1,2]) for jet_const in new_cut_data]
sums = [np.sum(jet_const[:4,0]) for jet_const in new_cut_data]
print(means_a)
print(means_b)
print(means_c)
print(means_a_)
print(means_b_)
print(means_c_)
print(sums)
print(type(means_a))

[0.8438056940131718, 0.6043575847390479, 0.39993009000062085, 0.651162744623324, 0.3848828952524548]
[0.21508228565421253, 0.2933041124010902, 0.2545993987739518, 0.30519418829191636, 0.25061492536523694]
[0.4152671355253024, 0.9305915189512699, 0.47521143801791466, 0.8068262347149068, 0.7300975822380785]
[0.8076373484062733, 0.7591107791547588, 0.2023124058816611, 0.5353533195446221, 0.4535565497622538]
[0.10286911689738365, 0.15526971767320052, 0.16898222169179455, 0.24367609070987142, 0.1520503637342021]
[0.15779017362619163, 0.8631180130219206, 0.09879336888222601, 0.8561205298940121, 0.6278269491664584]
[2.5314170820395154, 1.2087151694780958, 0.7998601800012417, 2.604650978493296, 1.1546486857573643]
<class 'list'>


In [52]:
feature_labels  = ['a','b','c']

def create_aggregated_feature(x_data, operation, feature, nb_const = None, sorted_feature='b', sort_ascending=True):
    try:
        sorted_feature_index = feature_labels.index(sorted_feature)
    except:
        print(f"'{sorted_feature}' not found in list of features!")
        return

    order = sort_ascending - (not sort_ascending)

    sorted_data = [x_data[i][(order*x_data[i][:, sorted_feature_index]).argsort()] for i in range(len(x_data))]
    
    try:
        feature_index = feature_labels.index(feature)
    except:
        print(f"'{feature}' not found in list of features!")
        return
    
    switcher = {
        "mean": lambda: [np.mean(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
        "median": lambda: [np.median(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
        "min": lambda: [np.amin(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
        "max": lambda: [np.amax(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
        "sum": lambda: [np.sum(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
    }

    aggregated_feature = switcher.get(operation, lambda: None)()
    if aggregated_feature is None:
        raise TypeError(f"'{operation}' not found from list of operations!")
    
    return aggregated_feature

def aggregate_all_features(x_data, operation):
    agg_feature_dict = {}
    
    for feature in feature_labels:
        agg_feature_dict[f'{feature}_{operation}'] = create_aggregated_feature(x_data, operation, feature)

    return agg_feature_dict

In [53]:
alt_means_ = create_aggregated_feature(new_cut_data, 'max', 'c', 3, sorted_feature='a', sort_ascending = True)
print(alt_means_)
alt_sums_ = create_aggregated_feature(new_cut_data, 'median', 'a', 4)
print(alt_sums_)

all_means = aggregate_all_features(new_cut_data, 'mean')
for feature in all_means:
    print(f'{feature}: {all_means[feature]}')
break_test = create_aggregated_feature(new_cut_data, 'me', 'd', 2)

[0.9302210593235242, 0.9980650248806193, 0.8516295071536033, 0.948262834618327, 0.9346388483813187]
[0.9161423852269688, 0.6043575847390479, 0.39993009000062085, 0.6724643763282622, 0.24753558623285676]
a_mean: [0.8438056940131718, 0.6043575847390479, 0.39993009000062085, 0.651162744623324, 0.3848828952524548]
b_mean: [0.21508228565421253, 0.2933041124010902, 0.2545993987739518, 0.30519418829191636, 0.25061492536523694]
c_mean: [0.4152671355253024, 0.9305915189512699, 0.47521143801791466, 0.8068262347149068, 0.7300975822380785]
'd' not found in list of features!


In [110]:
max_constituents = 4
new_nb_constituents = np.array([])

for jet in range(len(new_cut_data)):
    if new_cut_data[jet].shape[0] >= max_constituents:
        new_nb_constituents = np.append(new_nb_constituents, max_constituents)
        new_cut_data[jet] = new_cut_data[jet][:max_constituents, :]
    else:
        new_nb_constituents = np.append(new_nb_constituents, new_cut_data[jet].shape[0])
        padding_length = max_constituents - new_cut_data[jet].shape[0]
        new_cut_data[jet] = np.pad(new_cut_data[jet], ((0, padding_length), (0, 0)), constant_values = -0.999)
new_cut_data = np.array(new_cut_data)
print(new_cut_data)
print('\n===================\n')
print(new_nb_constituents)

[[[ 0.62329008  0.31537603  0.98695186]
  [ 0.2092492   0.37123428  0.07122857]
  [-0.999      -0.999      -0.999     ]
  [-0.999      -0.999      -0.999     ]]

 [[ 0.61153328  0.30160817  0.08293803]
  [-0.999      -0.999      -0.999     ]
  [-0.999      -0.999      -0.999     ]
  [-0.999      -0.999      -0.999     ]]

 [[ 0.20614618  0.23781982  0.07321044]
  [ 0.29814028  0.3613127   0.68847572]
  [ 0.75464347  0.48001996  0.3304572 ]
  [-0.999      -0.999      -0.999     ]]

 [[ 0.23920947  0.05308377  0.38631762]
  [ 0.21820527  0.16563036  0.03788958]
  [ 0.31354992  0.16757342  0.09224389]
  [ 0.96516806  0.19341745  0.0067916 ]]

 [[ 0.60452188  0.16031759  0.39418248]
  [ 0.50079443  0.25102322  0.03547827]
  [ 0.22961632  0.37072405  0.34178145]
  [-0.999      -0.999      -0.999     ]]]


[2. 1. 3. 4. 3.]


In [71]:
positive_class = 't'

In [85]:
bytes(positive_class, 'utf-8')

b't'

In [86]:
feature_labels = [
        "px",
        "py",
        "pz",
        "E",
        "E_rel",
        "pT",
        "pT_rel",
        "eta",
        "eta_rel",
        "eta_rot",
        "phi",
        "phi_rel",
        "phi_rot",
        "Delta_R",
        "cos(theta)",
        "cos(theta_rel)",
    ]

In [114]:
a = np.array([0,0,0,0])
print(a!=0)

[False False False False]


In [115]:
constituents_distribution = []
for jet in rand_data:
    const_nb = 0
    for const in jet:
        if const[0] != 0:
            const_nb += 1
    constituents_distribution.append(const_nb)

print(constituents_distribution)

[4, 4, 4, 4, 4]


In [6]:
np.arange(0,2,0.25)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75])

In [10]:
print(np.asarray(np.append(np.append(np.arange(0,2,0.25),np.arange(2,5,0.5)), np.arange(5,11,1))))

[ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.    2.5   3.    3.5
  4.    4.5   5.    6.    7.    8.    9.   10.  ]


In [7]:
import sys
import time

In [17]:
print('Starting process')

sys.stdout.write('\r')
# the exact output you're looking for:
sys.stdout.write("[%-20s] %d%%" % ('='*1, 5*1))
sys.stdout.flush()
time.sleep(0.5)

for i in range(2, 21):
    sys.stdout.write('\r')
    # the exact output you're looking for:
    sys.stdout.write("[%-20s] %d%%" % ('='*i, 5*i))
    sys.stdout.flush()
    time.sleep(0.5)

print('\nProcess complete')
    

Starting process
[====================] 100%
Process complete


In [15]:
a = 12
b= 'fish'

print(f'Hello {a}{b}')

Hello 12fish


In [72]:
a = np.array([[1]])
for i in range(4):
    a = np.concatenate((a,[[i]]), axis = 0)

print(a)

[[1]
 [0]
 [1]
 [2]
 [3]]


In [75]:
b = np.array([[9]])

for i in range(2,6):
    b = np.concatenate((b,[[i]]), axis = 0)

print(b)

[[9]
 [2]
 [3]
 [4]
 [5]]


In [74]:
print(np.concatenate((a,b), axis = 1))

[[1 9]
 [0 2]
 [1 3]
 [2 4]
 [3 5]]


In [4]:
c = np.array([])

for i in range(4):
    c = np.append(c, i)

print(c)

d = np.array([])

for i in range(5,9):
    d = np.append(d, i)

print(d)

e = np.concatenate(([c],[d]), axis =0)
print(e)

[0. 1. 2. 3.]
[5. 6. 7. 8.]
[[0. 1. 2. 3.]
 [5. 6. 7. 8.]]


In [5]:
np.swapaxes(e, 0, 1)

array([[0., 5.],
       [1., 6.],
       [2., 7.],
       [3., 8.]])

In [7]:
e[:,1]

array([1., 6.])

In [36]:
def combine_array(a1, a2):
    if np.ndim(a1) == 2:
        combined_array = np.concatenate((a1, [a2]), axis = 0)
    elif np.ndim(a1) == 1:
        combined_array = np.concatenate(([a1], [a2]), axis =1)

    return combined_array

In [32]:
f = np.array([])

f = np.concatenate(([f], [c]), axis = 1)
print(np.asarray(f))

f = np.concatenate((f,[d]), axis = 0)

print(np.asarray(f))

[[0. 1. 2. 3.]]
[[0. 1. 2. 3.]
 [5. 6. 7. 8.]]


In [28]:
np.ndim(c)

1

In [38]:
f = np.array([])

f = combine_array(f, c)
print(f)

f = combine_array(f,d)
print(f)

[[0. 1. 2. 3.]]
[[0. 1. 2. 3.]
 [5. 6. 7. 8.]]


In [5]:
import os

def get_file_paths(data_file_dir: str) -> list:
    """Gets path to the data files inside a given directory.

    Args:
        data_file_dir: Path to directory containing the data files.

    Returns:
        Array of paths to the data files themselves.
    """
    file_names = os.listdir(data_file_dir)
    print(file_names)
    file_paths = [os.path.join(data_file_dir, file_name) for file_name in file_names]

    return file_paths

In [6]:
get_file_paths('../Data/train/')

['jetImage_0_150p_40000_50000.h5', 'jetImage_4_150p_20000_30000.h5', 'jetImage_2_150p_50000_60000.h5', 'jetImage_5_150p_30000_40000.h5', 'jetImage_0_150p_70000_80000.h5', 'jetImage_3_150p_20000_30000.h5', 'jetImage_1_150p_0_10000.h5', 'jetImage_5_150p_50000_60000.h5', 'jetImage_2_150p_30000_40000.h5', 'jetImage_0_150p_0_10000.h5', 'jetImage_1_150p_80000_90000.h5', 'jetImage_1_150p_10000_20000.h5', 'jetImage_0_150p_60000_70000.h5', 'jetImage_6_150p_10000_20000.h5', 'jetImage_6_150p_80000_90000.h5', 'jetImage_0_150p_20000_30000.h5', 'jetImage_3_150p_70000_80000.h5', 'jetImage_1_150p_30000_40000.h5', 'jetImage_6_150p_50000_60000.h5', 'jetImage_3_150p_0_10000.h5', 'jetImage_4_150p_70000_80000.h5', 'jetImage_6_150p_30000_40000.h5', 'jetImage_1_150p_50000_60000.h5', 'jetImage_4_150p_40000_50000.h5', 'jetImage_3_150p_40000_50000.h5', 'jetImage_3_150p_60000_70000.h5', 'jetImage_5_150p_80000_90000.h5', 'jetImage_5_150p_10000_20000.h5', 'jetImage_2_150p_0_10000.h5', 'jetImage_4_150p_60000_70000.

['../Data/train/jetImage_0_150p_40000_50000.h5',
 '../Data/train/jetImage_4_150p_20000_30000.h5',
 '../Data/train/jetImage_2_150p_50000_60000.h5',
 '../Data/train/jetImage_5_150p_30000_40000.h5',
 '../Data/train/jetImage_0_150p_70000_80000.h5',
 '../Data/train/jetImage_3_150p_20000_30000.h5',
 '../Data/train/jetImage_1_150p_0_10000.h5',
 '../Data/train/jetImage_5_150p_50000_60000.h5',
 '../Data/train/jetImage_2_150p_30000_40000.h5',
 '../Data/train/jetImage_0_150p_0_10000.h5',
 '../Data/train/jetImage_1_150p_80000_90000.h5',
 '../Data/train/jetImage_1_150p_10000_20000.h5',
 '../Data/train/jetImage_0_150p_60000_70000.h5',
 '../Data/train/jetImage_6_150p_10000_20000.h5',
 '../Data/train/jetImage_6_150p_80000_90000.h5',
 '../Data/train/jetImage_0_150p_20000_30000.h5',
 '../Data/train/jetImage_3_150p_70000_80000.h5',
 '../Data/train/jetImage_1_150p_30000_40000.h5',
 '../Data/train/jetImage_6_150p_50000_60000.h5',
 '../Data/train/jetImage_3_150p_0_10000.h5',
 '../Data/train/jetImage_4_150p_

In [12]:
1%5

1

In [13]:
5%5

0

In [14]:
9%5

4

In [16]:
print('\rtest', flush = True)
print('\rcheese', flush = True)

test
cheese


In [36]:
from terminal_colors import tcols

a = True
print(tcols.FAIL+f'I just came to say {a*"hello"+(not a)*"goodbye"}'+tcols.ENDC)

I just came to say hello


In [1]:
def rah(fam:str='cheese'):
    print(fam)

In [2]:
rah()

cheese


In [3]:
rah('geezer')

geezer


In [7]:
true_class = [[True],[False], [True]]
df = pd.DataFrame(data = true_class, columns = ['class'])

In [8]:
df

class
0   True
1  False
2   True

In [10]:
df['class'] * 1

0    1
1    0
2    1
Name: class, dtype: int64

In [11]:
true_class

[[True], [False], [True]]

In [21]:
other_class = [[False], [False], [True]]

In [22]:
print(true_class and other_class)

[[False], [False], [True]]


In [6]:
a = [[1,2,2,3,4,1],[5,4,6,1,2,2]]

In [44]:
np.pad(a, ((1,2), (3,4)), constant_values= ((-99,20),(12,-9)))

array([[ 12,  12,  12, -99, -99, -99, -99, -99, -99,  -9,  -9,  -9,  -9],
       [ 12,  12,  12,   1,   2,   2,   3,   4,   1,  -9,  -9,  -9,  -9],
       [ 12,  12,  12,   5,   4,   6,   1,   2,   2,  -9,  -9,  -9,  -9],
       [ 12,  12,  12,  20,  20,  20,  20,  20,  20,  -9,  -9,  -9,  -9],
       [ 12,  12,  12,  20,  20,  20,  20,  20,  20,  -9,  -9,  -9,  -9]])

In [2]:
b = [1,2,3,1,2,1]

In [51]:
b[:None]

[1, 2, 3, 1, 2, 1]

In [15]:
import pandas as pd
df = pd.DataFrame(a, columns = ['a', 'b', 'c', 'd', 'e', 'f'])

In [18]:
df['new'] = [8,1]

In [19]:
df

a  b  c  d  e  f  new
0  1  2  2  3  4  1    8
1  5  4  6  1  2  2    1

In [25]:
import numpy as np
np.mean(b[:4])

1.75

In [4]:
dic = {}

In [5]:
dic['b'] = b 

In [6]:
dic

{'b': [1, 2, 3, 1, 2, 1]}

In [7]:
dic['b']

[1, 2, 3, 1, 2, 1]

In [8]:
dic['a'] = 'hello'

In [9]:
dic

{'b': [1, 2, 3, 1, 2, 1], 'a': 'hello'}

In [11]:
for item in dic:
    print(dic[item])

[1, 2, 3, 1, 2, 1]
hello
