In [1]:
import numpy as np
import pandas as pd

In [66]:
data = [[1.3,6.2,7.3,], [4.2,8.1,0.3], [3.7,1.1,2.8], [13.2,8.2,3.1,], [1.3,5.1,3.9], [3.2,4.1,12.5]]

heading = ['a', 'b', 'c']

ohe_data = np.array([[0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 0, 1],
 [0, 1, 0, 0, 0]])

classes = np.array([b'g', b'q', b'w', b'z', b't'])

In [68]:
y_data = [np.argmax(ohe_array) for ohe_array in ohe_data]
print(y_data)

[3, 0, 2, 2, 4, 1]


In [2]:
rand_data = np.random.rand(5,6,3)
rand_class = np.random.randint(0,5,5)
#big_rand_data = np.random.rand(620000,50,16)
print(rand_data)
print(rand_class)

[[[0.30194989 0.78501522 0.76785954]
  [0.82537798 0.01491811 0.38499032]
  [0.60091059 0.15292312 0.83453613]
  [0.56556327 0.25175678 0.25182691]
  [0.36968028 0.05894669 0.00288249]
  [0.94508682 0.74759897 0.48268895]]

 [[0.00847085 0.24273813 0.39808676]
  [0.9529521  0.19002575 0.25506157]
  [0.20466712 0.86579043 0.36311837]
  [0.22328282 0.88973468 0.65028586]
  [0.96271002 0.08544198 0.01654267]
  [0.78338736 0.18174495 0.16797839]]

 [[0.91331203 0.04092594 0.85507386]
  [0.28727678 0.67360399 0.9895451 ]
  [0.8814514  0.63301846 0.72155127]
  [0.51558262 0.88122669 0.76646486]
  [0.41437063 0.0292482  0.95640661]
  [0.35268858 0.83407648 0.80402081]]

 [[0.28936301 0.85923633 0.28667838]
  [0.8436809  0.48434738 0.22359089]
  [0.3025417  0.70846336 0.18842054]
  [0.00927064 0.20250938 0.27009199]
  [0.99948886 0.57407474 0.97544327]
  [0.49890757 0.8913143  0.11456469]]

 [[0.08422486 0.03985206 0.53189105]
  [0.13935952 0.74696637 0.84115709]
  [0.24397822 0.81748003 0.321

In [3]:
ascending = False
order = ascending - (not ascending)
print(order)

-1


In [4]:
sorted_data = np.array([rand_data[i][(order*rand_data[i][:, 0]).argsort()] for i in range(len(rand_data))])
#big_sorted_data = np.asarray([big_rand_data[i][big_rand_data[i][:, 1].argsort()] for i in range(len(big_rand_data))])

print(sorted_data)
print(type(sorted_data))

[[[0.94508682 0.74759897 0.48268895]
  [0.82537798 0.01491811 0.38499032]
  [0.60091059 0.15292312 0.83453613]
  [0.56556327 0.25175678 0.25182691]
  [0.36968028 0.05894669 0.00288249]
  [0.30194989 0.78501522 0.76785954]]

 [[0.96271002 0.08544198 0.01654267]
  [0.9529521  0.19002575 0.25506157]
  [0.78338736 0.18174495 0.16797839]
  [0.22328282 0.88973468 0.65028586]
  [0.20466712 0.86579043 0.36311837]
  [0.00847085 0.24273813 0.39808676]]

 [[0.91331203 0.04092594 0.85507386]
  [0.8814514  0.63301846 0.72155127]
  [0.51558262 0.88122669 0.76646486]
  [0.41437063 0.0292482  0.95640661]
  [0.35268858 0.83407648 0.80402081]
  [0.28727678 0.67360399 0.9895451 ]]

 [[0.99948886 0.57407474 0.97544327]
  [0.8436809  0.48434738 0.22359089]
  [0.49890757 0.8913143  0.11456469]
  [0.3025417  0.70846336 0.18842054]
  [0.28936301 0.85923633 0.28667838]
  [0.00927064 0.20250938 0.27009199]]

 [[0.9193206  0.21477141 0.81069787]
  [0.24397822 0.81748003 0.32137213]
  [0.13935952 0.74696637 0.841

In [5]:
boolean_index = [True, False, False, True, False]

print(sorted_data[:,:,1][boolean_index].flatten())

[0.74759897 0.01491811 0.15292312 0.25175678 0.05894669 0.78501522
 0.57407474 0.48434738 0.8913143  0.70846336 0.85923633 0.20250938]


In [6]:
print(boolean_index)
print(1*(boolean_index))

[True, False, False, True, False]
[True, False, False, True, False]


In [7]:
boolean_mask = sorted_data[:, :, 0] > 0.2
structure_memory = boolean_mask.sum(axis=1)

In [8]:
print(boolean_mask)
print(structure_memory)
print(np.mean(structure_memory))

[[ True  True  True  True  True  True]
 [ True  True  True  True  True False]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True False]
 [ True  True False False False False]]
[6 5 6 5 2]
4.8


In [9]:
cut_data = np.split(sorted_data[boolean_mask, :], np.cumsum(structure_memory)[:-1])

print(cut_data)
print('\n================\n')
cut_data = [jet_const for jet_const in cut_data if jet_const.size > 0]

print(cut_data)

[array([[0.94508682, 0.74759897, 0.48268895],
       [0.82537798, 0.01491811, 0.38499032],
       [0.60091059, 0.15292312, 0.83453613],
       [0.56556327, 0.25175678, 0.25182691],
       [0.36968028, 0.05894669, 0.00288249],
       [0.30194989, 0.78501522, 0.76785954]]), array([[0.96271002, 0.08544198, 0.01654267],
       [0.9529521 , 0.19002575, 0.25506157],
       [0.78338736, 0.18174495, 0.16797839],
       [0.22328282, 0.88973468, 0.65028586],
       [0.20466712, 0.86579043, 0.36311837]]), array([[0.91331203, 0.04092594, 0.85507386],
       [0.8814514 , 0.63301846, 0.72155127],
       [0.51558262, 0.88122669, 0.76646486],
       [0.41437063, 0.0292482 , 0.95640661],
       [0.35268858, 0.83407648, 0.80402081],
       [0.28727678, 0.67360399, 0.9895451 ]]), array([[0.99948886, 0.57407474, 0.97544327],
       [0.8436809 , 0.48434738, 0.22359089],
       [0.49890757, 0.8913143 , 0.11456469],
       [0.3025417 , 0.70846336, 0.18842054],
       [0.28936301, 0.85923633, 0.28667838]]), a

In [10]:
max_constituents = 6
nb_constituents = np.array([])

for jet in range(len(cut_data)):
    if cut_data[jet].shape[0] >= max_constituents:
        nb_constituents = np.append(nb_constituents, max_constituents)
        cut_data[jet] = cut_data[jet][:max_constituents, :]
    else:
        nb_constituents = np.append(nb_constituents, cut_data[jet].shape[0])
        padding_length = max_constituents - cut_data[jet].shape[0]
        cut_data[jet] = np.pad(cut_data[jet], ((0, padding_length), (0, 0)), constant_values = 0)
cut_data = np.array(cut_data)
print(cut_data)
print('\n===================\n')
print(nb_constituents)

[[[0.94508682 0.74759897 0.48268895]
  [0.82537798 0.01491811 0.38499032]
  [0.60091059 0.15292312 0.83453613]
  [0.56556327 0.25175678 0.25182691]
  [0.36968028 0.05894669 0.00288249]
  [0.30194989 0.78501522 0.76785954]]

 [[0.96271002 0.08544198 0.01654267]
  [0.9529521  0.19002575 0.25506157]
  [0.78338736 0.18174495 0.16797839]
  [0.22328282 0.88973468 0.65028586]
  [0.20466712 0.86579043 0.36311837]
  [0.         0.         0.        ]]

 [[0.91331203 0.04092594 0.85507386]
  [0.8814514  0.63301846 0.72155127]
  [0.51558262 0.88122669 0.76646486]
  [0.41437063 0.0292482  0.95640661]
  [0.35268858 0.83407648 0.80402081]
  [0.28727678 0.67360399 0.9895451 ]]

 [[0.99948886 0.57407474 0.97544327]
  [0.8436809  0.48434738 0.22359089]
  [0.49890757 0.8913143  0.11456469]
  [0.3025417  0.70846336 0.18842054]
  [0.28936301 0.85923633 0.28667838]
  [0.         0.         0.        ]]

 [[0.9193206  0.21477141 0.81069787]
  [0.24397822 0.81748003 0.32137213]
  [0.         0.         0.   

In [16]:
cut_data[:2]

array([[[0.94508682, 0.74759897, 0.48268895],
        [0.82537798, 0.01491811, 0.38499032],
        [0.60091059, 0.15292312, 0.83453613],
        [0.56556327, 0.25175678, 0.25182691],
        [0.36968028, 0.05894669, 0.00288249],
        [0.30194989, 0.78501522, 0.76785954]],

       [[0.96271002, 0.08544198, 0.01654267],
        [0.9529521 , 0.19002575, 0.25506157],
        [0.78338736, 0.18174495, 0.16797839],
        [0.22328282, 0.88973468, 0.65028586],
        [0.20466712, 0.86579043, 0.36311837],
        [0.        , 0.        , 0.        ]]])

In [11]:
is_not_padded = np.any(cut_data, axis = 2)
print(is_not_padded)
constituent_memory = is_not_padded.sum(axis = 1)
print(constituent_memory)
# is_positive_class = [True, False, False, True, False]
# print(is_positive_class)

[[ True  True  True  True  True  True]
 [ True  True  True  True  True False]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True False]
 [ True  True False False False False]]
[6 5 6 5 2]


In [12]:
print(cut_data[is_not_padded, :])

[[0.94508682 0.74759897 0.48268895]
 [0.82537798 0.01491811 0.38499032]
 [0.60091059 0.15292312 0.83453613]
 [0.56556327 0.25175678 0.25182691]
 [0.36968028 0.05894669 0.00288249]
 [0.30194989 0.78501522 0.76785954]
 [0.96271002 0.08544198 0.01654267]
 [0.9529521  0.19002575 0.25506157]
 [0.78338736 0.18174495 0.16797839]
 [0.22328282 0.88973468 0.65028586]
 [0.20466712 0.86579043 0.36311837]
 [0.91331203 0.04092594 0.85507386]
 [0.8814514  0.63301846 0.72155127]
 [0.51558262 0.88122669 0.76646486]
 [0.41437063 0.0292482  0.95640661]
 [0.35268858 0.83407648 0.80402081]
 [0.28727678 0.67360399 0.9895451 ]
 [0.99948886 0.57407474 0.97544327]
 [0.8436809  0.48434738 0.22359089]
 [0.49890757 0.8913143  0.11456469]
 [0.3025417  0.70846336 0.18842054]
 [0.28936301 0.85923633 0.28667838]
 [0.9193206  0.21477141 0.81069787]
 [0.24397822 0.81748003 0.32137213]]


In [13]:
print(rand_class)
large_class = np.array([], dtype = int)
cut_data[1]

for i in range(len(constituent_memory)):
    print(i)
    large_class = np.append(large_class, constituent_memory[i]*[rand_class[i]])

print(large_class)

[2 3 4 1 0]
0
1
2
3
4
[2 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4 4 1 1 1 1 1 0 0]


In [14]:
print(cut_data[is_not_padded, :])
print(len(cut_data[is_not_padded, :]))
print(large_class)
print(len(large_class))
print(large_class.reshape(len(large_class), 1))

np.concatenate((cut_data[is_not_padded, :], large_class.reshape(len(large_class), 1)), axis =1)

[[0.94508682 0.74759897 0.48268895]
 [0.82537798 0.01491811 0.38499032]
 [0.60091059 0.15292312 0.83453613]
 [0.56556327 0.25175678 0.25182691]
 [0.36968028 0.05894669 0.00288249]
 [0.30194989 0.78501522 0.76785954]
 [0.96271002 0.08544198 0.01654267]
 [0.9529521  0.19002575 0.25506157]
 [0.78338736 0.18174495 0.16797839]
 [0.22328282 0.88973468 0.65028586]
 [0.20466712 0.86579043 0.36311837]
 [0.91331203 0.04092594 0.85507386]
 [0.8814514  0.63301846 0.72155127]
 [0.51558262 0.88122669 0.76646486]
 [0.41437063 0.0292482  0.95640661]
 [0.35268858 0.83407648 0.80402081]
 [0.28727678 0.67360399 0.9895451 ]
 [0.99948886 0.57407474 0.97544327]
 [0.8436809  0.48434738 0.22359089]
 [0.49890757 0.8913143  0.11456469]
 [0.3025417  0.70846336 0.18842054]
 [0.28936301 0.85923633 0.28667838]
 [0.9193206  0.21477141 0.81069787]
 [0.24397822 0.81748003 0.32137213]]
24
[2 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4 4 1 1 1 1 1 0 0]
24
[[2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [3]
 [3]
 [3]
 [3]
 [3]
 [4]
 [4]
 [4]
 [4]
 [4]

array([[9.45086819e-01, 7.47598966e-01, 4.82688952e-01, 2.00000000e+00],
       [8.25377981e-01, 1.49181144e-02, 3.84990322e-01, 2.00000000e+00],
       [6.00910594e-01, 1.52923118e-01, 8.34536130e-01, 2.00000000e+00],
       [5.65563273e-01, 2.51756779e-01, 2.51826905e-01, 2.00000000e+00],
       [3.69680278e-01, 5.89466882e-02, 2.88248611e-03, 2.00000000e+00],
       [3.01949892e-01, 7.85015222e-01, 7.67859538e-01, 2.00000000e+00],
       [9.62710021e-01, 8.54419805e-02, 1.65426695e-02, 3.00000000e+00],
       [9.52952105e-01, 1.90025749e-01, 2.55061573e-01, 3.00000000e+00],
       [7.83387357e-01, 1.81744950e-01, 1.67978391e-01, 3.00000000e+00],
       [2.23282824e-01, 8.89734682e-01, 6.50285856e-01, 3.00000000e+00],
       [2.04667115e-01, 8.65790433e-01, 3.63118371e-01, 3.00000000e+00],
       [9.13312035e-01, 4.09259358e-02, 8.55073857e-01, 4.00000000e+00],
       [8.81451397e-01, 6.33018462e-01, 7.21551270e-01, 4.00000000e+00],
       [5.15582620e-01, 8.81226694e-01, 7.66464857e

In [15]:
cut_boolean_mask = cut_data[:, :, 1] < 0.5
print(cut_boolean_mask)

[[False  True  True  True  True False]
 [ True  True  True False False  True]
 [ True False False  True False False]
 [False  True False False False  True]
 [ True False  True  True  True  True]]


In [13]:
new_boolean_mask = cut_boolean_mask * is_not_padded
new_structure_memory = new_boolean_mask.sum(axis = 1)
print(new_boolean_mask)
print(new_structure_memory)

[[False False False False False False]
 [False  True False False False False]
 [ True  True  True  True False False]
 [False False  True False False False]
 [ True  True  True False False False]]
[0 1 4 1 3]


In [30]:
new_cut_data = np.split(cut_data[new_boolean_mask, :], np.cumsum(new_structure_memory)[:-1])
print(new_cut_data)

# new_cut_data = [jet_const for jet_const in new_cut_data if jet_const.size >0]
# print(new_cut_data)

ascending = True
order = ascending - (not ascending)

new_cut_data = [new_cut_data[i][(order*new_cut_data[i][:, 1]).argsort()] for i in range(len(new_cut_data))]

print('-----------------')
print(new_cut_data)
print(type(new_cut_data))

[array([[0.31096717, 0.19810237, 0.9584172 ]]), array([[0.55501169, 0.24169078, 0.91067052],
       [0.23784861, 0.05837725, 0.06358404],
       [0.22099701, 0.0475618 , 0.9945953 ]]), array([[0.67377265, 0.14582521, 0.25992718],
       [0.60179192, 0.02465442, 0.22187714]]), array([[0.93891831, 0.24385523, 0.26970766],
       [0.79101309, 0.18717309, 0.02891489]]), array([[0.90123358, 0.07322485, 0.19132789],
       [0.49177459, 0.12306054, 0.63115467],
       [0.40722695, 0.32317744, 0.99055728]])]
-----------------
[array([[0.31096717, 0.19810237, 0.9584172 ]]), array([[0.22099701, 0.0475618 , 0.9945953 ],
       [0.23784861, 0.05837725, 0.06358404],
       [0.55501169, 0.24169078, 0.91067052]]), array([[0.60179192, 0.02465442, 0.22187714],
       [0.67377265, 0.14582521, 0.25992718]]), array([[0.79101309, 0.18717309, 0.02891489],
       [0.93891831, 0.24385523, 0.26970766]]), array([[0.90123358, 0.07322485, 0.19132789],
       [0.49177459, 0.12306054, 0.63115467],
       [0.4072269

In [32]:
a = [jet_const[:,[0,2]]for jet_const in new_cut_data]
print(a)

[array([[0.31096717, 0.9584172 ]]), array([[0.22099701, 0.9945953 ],
       [0.23784861, 0.06358404],
       [0.55501169, 0.91067052]]), array([[0.60179192, 0.22187714],
       [0.67377265, 0.25992718]]), array([[0.79101309, 0.02891489],
       [0.93891831, 0.26970766]]), array([[0.90123358, 0.19132789],
       [0.49177459, 0.63115467],
       [0.40722695, 0.99055728]])]


In [47]:
for jet_const in new_cut_data:
    print(jet_const[:,0])
    print(jet_const[:-1,0])

[0.97871777 0.63655692 0.91614239]
[0.97871777 0.63655692]
[0.75911078 0.44960439]
[0.75911078]
[0.20231241 0.59754777]
[0.20231241]
[0.26113121 0.74083859 0.60409017 0.99859102]
[0.26113121 0.74083859 0.60409017]
[0.21209679 0.69501631 0.24753559]
[0.21209679 0.69501631]


In [46]:
means_a = [np.mean(jet_const[:,0]) for jet_const in new_cut_data]
means_b = [np.mean(jet_const[:,1]) for jet_const in new_cut_data]
means_c = [np.mean(jet_const[:,2]) for jet_const in new_cut_data]
means_a_ = [np.mean(jet_const[:-1,0]) for jet_const in new_cut_data]
means_b_ = [np.mean(jet_const[:-1,1]) for jet_const in new_cut_data]
means_c_ = [np.mean(jet_const[:-1,2]) for jet_const in new_cut_data]
sums = [np.sum(jet_const[:4,0]) for jet_const in new_cut_data]
print(means_a)
print(means_b)
print(means_c)
print(means_a_)
print(means_b_)
print(means_c_)
print(sums)
print(type(means_a))

[0.8438056940131718, 0.6043575847390479, 0.39993009000062085, 0.651162744623324, 0.3848828952524548]
[0.21508228565421253, 0.2933041124010902, 0.2545993987739518, 0.30519418829191636, 0.25061492536523694]
[0.4152671355253024, 0.9305915189512699, 0.47521143801791466, 0.8068262347149068, 0.7300975822380785]
[0.8076373484062733, 0.7591107791547588, 0.2023124058816611, 0.5353533195446221, 0.4535565497622538]
[0.10286911689738365, 0.15526971767320052, 0.16898222169179455, 0.24367609070987142, 0.1520503637342021]
[0.15779017362619163, 0.8631180130219206, 0.09879336888222601, 0.8561205298940121, 0.6278269491664584]
[2.5314170820395154, 1.2087151694780958, 0.7998601800012417, 2.604650978493296, 1.1546486857573643]
<class 'list'>


In [52]:
feature_labels  = ['a','b','c']

def create_aggregated_feature(x_data, operation, feature, nb_const = None, sorted_feature='b', sort_ascending=True):
    try:
        sorted_feature_index = feature_labels.index(sorted_feature)
    except:
        print(f"'{sorted_feature}' not found in list of features!")
        return

    order = sort_ascending - (not sort_ascending)

    sorted_data = [x_data[i][(order*x_data[i][:, sorted_feature_index]).argsort()] for i in range(len(x_data))]
    
    try:
        feature_index = feature_labels.index(feature)
    except:
        print(f"'{feature}' not found in list of features!")
        return
    
    switcher = {
        "mean": lambda: [np.mean(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
        "median": lambda: [np.median(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
        "min": lambda: [np.amin(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
        "max": lambda: [np.amax(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
        "sum": lambda: [np.sum(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
    }

    aggregated_feature = switcher.get(operation, lambda: None)()
    if aggregated_feature is None:
        raise TypeError(f"'{operation}' not found from list of operations!")
    
    return aggregated_feature

def aggregate_all_features(x_data, operation):
    agg_feature_dict = {}
    
    for feature in feature_labels:
        agg_feature_dict[f'{feature}_{operation}'] = create_aggregated_feature(x_data, operation, feature)

    return agg_feature_dict

In [53]:
alt_means_ = create_aggregated_feature(new_cut_data, 'max', 'c', 3, sorted_feature='a', sort_ascending = True)
print(alt_means_)
alt_sums_ = create_aggregated_feature(new_cut_data, 'median', 'a', 4)
print(alt_sums_)

all_means = aggregate_all_features(new_cut_data, 'mean')
for feature in all_means:
    print(f'{feature}: {all_means[feature]}')
break_test = create_aggregated_feature(new_cut_data, 'me', 'd', 2)

[0.9302210593235242, 0.9980650248806193, 0.8516295071536033, 0.948262834618327, 0.9346388483813187]
[0.9161423852269688, 0.6043575847390479, 0.39993009000062085, 0.6724643763282622, 0.24753558623285676]
a_mean: [0.8438056940131718, 0.6043575847390479, 0.39993009000062085, 0.651162744623324, 0.3848828952524548]
b_mean: [0.21508228565421253, 0.2933041124010902, 0.2545993987739518, 0.30519418829191636, 0.25061492536523694]
c_mean: [0.4152671355253024, 0.9305915189512699, 0.47521143801791466, 0.8068262347149068, 0.7300975822380785]
'd' not found in list of features!


In [110]:
max_constituents = 4
new_nb_constituents = np.array([])

for jet in range(len(new_cut_data)):
    if new_cut_data[jet].shape[0] >= max_constituents:
        new_nb_constituents = np.append(new_nb_constituents, max_constituents)
        new_cut_data[jet] = new_cut_data[jet][:max_constituents, :]
    else:
        new_nb_constituents = np.append(new_nb_constituents, new_cut_data[jet].shape[0])
        padding_length = max_constituents - new_cut_data[jet].shape[0]
        new_cut_data[jet] = np.pad(new_cut_data[jet], ((0, padding_length), (0, 0)), constant_values = -0.999)
new_cut_data = np.array(new_cut_data)
print(new_cut_data)
print('\n===================\n')
print(new_nb_constituents)

[[[ 0.62329008  0.31537603  0.98695186]
  [ 0.2092492   0.37123428  0.07122857]
  [-0.999      -0.999      -0.999     ]
  [-0.999      -0.999      -0.999     ]]

 [[ 0.61153328  0.30160817  0.08293803]
  [-0.999      -0.999      -0.999     ]
  [-0.999      -0.999      -0.999     ]
  [-0.999      -0.999      -0.999     ]]

 [[ 0.20614618  0.23781982  0.07321044]
  [ 0.29814028  0.3613127   0.68847572]
  [ 0.75464347  0.48001996  0.3304572 ]
  [-0.999      -0.999      -0.999     ]]

 [[ 0.23920947  0.05308377  0.38631762]
  [ 0.21820527  0.16563036  0.03788958]
  [ 0.31354992  0.16757342  0.09224389]
  [ 0.96516806  0.19341745  0.0067916 ]]

 [[ 0.60452188  0.16031759  0.39418248]
  [ 0.50079443  0.25102322  0.03547827]
  [ 0.22961632  0.37072405  0.34178145]
  [-0.999      -0.999      -0.999     ]]]


[2. 1. 3. 4. 3.]


In [71]:
positive_class = 't'

In [85]:
bytes(positive_class, 'utf-8')

b't'

In [2]:
feature_labels = [
        "px",
        "py",
        "pz",
        "E",
        "E_rel",
        "pT",
        "pT_rel",
        "eta",
        "eta_rel",
        "eta_rot",
        "phi",
        "phi_rel",
        "phi_rot",
        "Delta_R",
        "cos(theta)",
        "cos(theta_rel)",
    ]

In [7]:
from prepare_data_BDT import select_feature_labels

andre_features = select_feature_labels('andre')
jedinet_features = select_feature_labels('jedinet')

In [13]:
indices = []

for feature in select_feature_labels('andre'):
    index = select_feature_labels('jedinet').index(feature)
    indices.append(index)

print(indices)

[5, 8, 11]


In [7]:
import sys
import time

In [17]:
print('Starting process')

sys.stdout.write('\r')
# the exact output you're looking for:
sys.stdout.write("[%-20s] %d%%" % ('='*1, 5*1))
sys.stdout.flush()
time.sleep(0.5)

for i in range(2, 21):
    sys.stdout.write('\r')
    # the exact output you're looking for:
    sys.stdout.write("[%-20s] %d%%" % ('='*i, 5*i))
    sys.stdout.flush()
    time.sleep(0.5)

print('\nProcess complete')
    

Starting process
[====================] 100%
Process complete


In [36]:
from terminal_colors import tcols

a = True
print(tcols.FAIL+f'I just came to say {a*"hello"+(not a)*"goodbye"}'+tcols.ENDC)

I just came to say hello


In [33]:
df = pd.DataFrame()

In [34]:
df

Empty DataFrame
Columns: []
Index: []

In [35]:
df['rah'] = 69

In [37]:
df

Empty DataFrame
Columns: [rah]
Index: []

In [40]:
6 != 3

True

In [2]:
a = 5

In [4]:
b = str(a)

In [5]:
int(b)

5

In [20]:
nb_constituents = 'test'

try:
    print(f"Taking first {int(nb_constituents)} constituents")

except:
    print(f"Choosing from predified list: {nb_constituents}")

Choosing from predified list: test


In [17]:
def test_func(a, b, c):
    summed = a + b + c
    product = a * b * c
    quad = a**2 + b**2 + c**2
    quad1 = a**2 + b**2 - c**2

    return (summed, product,
            quad, quad1)

In [24]:
(summed, product, 
 quad, quad1) = test_func(1, 2, 3)
print(test_func(1, 2, 3))

(6, 6, 14, -4)


In [25]:
print(summed)
print(product)
print(quad)
print(quad1)

6
6
14
-4


In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3,1,2,1])

In [6]:
np.split(a, [2])

[array([1, 2]), array([3, 1, 2, 1])]

In [14]:
print("\033[4m"+"Beginning list:"+"\033[0m"+"\n\u2022 Hello mate\n\u2022 Geezer")

Beginning list:
• Hello mate
• Geezer


In [12]:
def test_function(arg1: list[int] = None):
    print(arg1)
    print(type(arg1))

    print(len(arg1))

    for arg in arg1:
        print(arg)

In [16]:
test_function([2,1,4])

[2, 1, 4]
<class 'list'>
3
2
1
4


In [17]:
a = [1,2]

In [19]:
type(a) == list

True

In [28]:
print( "\033[98m oi")

 oi
