In [1]:
import numpy as np
import pandas as pd

In [66]:
data = [[1.3,6.2,7.3,], [4.2,8.1,0.3], [3.7,1.1,2.8], [13.2,8.2,3.1,], [1.3,5.1,3.9], [3.2,4.1,12.5]]

heading = ['a', 'b', 'c']

ohe_data = np.array([[0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 0, 1],
 [0, 1, 0, 0, 0]])

classes = np.array([b'g', b'q', b'w', b'z', b't'])

In [68]:
y_data = [np.argmax(ohe_array) for ohe_array in ohe_data]
print(y_data)

[3, 0, 2, 2, 4, 1]


In [24]:
rand_data = np.random.rand(5,6,3)
rand_class = np.random.randint(0,5,5)
#big_rand_data = np.random.rand(620000,50,16)
print(rand_data)
print(rand_class)

[[[0.87183864 0.84101017 0.24094368]
  [0.23368093 0.33631054 0.47359517]
  [0.33404065 0.36549049 0.12254761]
  [0.09241623 0.79347292 0.337087  ]
  [0.72214438 0.92014478 0.76261645]
  [0.22355133 0.11993927 0.20939421]]

 [[0.50619094 0.39119054 0.02140552]
  [0.49999038 0.25823692 0.37850753]
  [0.99551455 0.53848399 0.41578403]
  [0.08774468 0.28166052 0.77900456]
  [0.03943875 0.70606653 0.00832279]
  [0.92158766 0.32538816 0.05685253]]

 [[0.84306619 0.08248026 0.54609825]
  [0.08684022 0.54315835 0.72550184]
  [0.57571394 0.64416923 0.68562272]
  [0.58856029 0.95972065 0.62693807]
  [0.40854049 0.1657114  0.58544405]
  [0.96623217 0.51049143 0.17508555]]

 [[0.27449287 0.45938343 0.25766775]
  [0.23711458 0.84643439 0.94692066]
  [0.28785168 0.34532988 0.45412833]
  [0.23875237 0.91082125 0.90597377]
  [0.84385068 0.28762858 0.32098236]
  [0.36497847 0.97664808 0.92135538]]

 [[0.55307675 0.26961909 0.28880102]
  [0.0439751  0.73539288 0.19315201]
  [0.70045695 0.41643087 0.522

In [14]:
ascending = False
order = ascending - (not ascending)
print(order)

-1


In [15]:
sorted_data = np.array([rand_data[i][(order*rand_data[i][:, 0]).argsort()] for i in range(len(rand_data))])
#big_sorted_data = np.asarray([big_rand_data[i][big_rand_data[i][:, 1].argsort()] for i in range(len(big_rand_data))])

print(sorted_data)
print(type(sorted_data))

[[[0.97807979 0.00117104 0.71172398]
  [0.96379767 0.86715605 0.2173511 ]
  [0.65462524 0.44441134 0.46172768]
  [0.53445562 0.68013254 0.39513529]
  [0.3442667  0.49736153 0.6199436 ]
  [0.03684299 0.51766745 0.13099243]]

 [[0.82502873 0.76993095 0.98115178]
  [0.45679646 0.5821968  0.87446563]
  [0.43551199 0.2502537  0.69733654]
  [0.2416555  0.54040756 0.17380207]
  [0.16398435 0.52180762 0.31953963]
  [0.12935104 0.38858331 0.05667905]]

 [[0.98650006 0.04794429 0.46993849]
  [0.81366201 0.42339047 0.04457746]
  [0.61971309 0.37085694 0.60514442]
  [0.53837013 0.50864835 0.1282322 ]
  [0.22942563 0.85755679 0.45045667]
  [0.15094214 0.08665505 0.26636464]]

 [[0.93317273 0.55193032 0.11748172]
  [0.8252512  0.35326552 0.83598052]
  [0.77822397 0.19413064 0.53467083]
  [0.52921853 0.28063085 0.42016388]
  [0.35457106 0.27425754 0.18450468]
  [0.34232631 0.548164   0.43214091]]

 [[0.99595068 0.94088614 0.32342719]
  [0.97163663 0.05751387 0.68021434]
  [0.71348403 0.51383027 0.947

In [16]:
boolean_index = [True, False, False, True, False]

print(sorted_data[:,:,1][boolean_index].flatten())

[0.00117104 0.86715605 0.44441134 0.68013254 0.49736153 0.51766745
 0.55193032 0.35326552 0.19413064 0.28063085 0.27425754 0.548164  ]


In [17]:
print(boolean_index)
print(1*(boolean_index))

[True, False, False, True, False]
[True, False, False, True, False]


In [18]:
boolean_mask = sorted_data[:, :, 0] > 0.2
structure_memory = boolean_mask.sum(axis=1)

In [19]:
print(boolean_mask)
print(structure_memory)
print(np.mean(structure_memory))

[[ True  True  True  True  True False]
 [ True  True  True  True False False]
 [ True  True  True  True  True False]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
[5 4 5 6 6]
5.2


In [20]:
cut_data = np.split(sorted_data[boolean_mask, :], np.cumsum(structure_memory)[:-1])

print(cut_data)
print('\n================\n')
cut_data = [jet_const for jet_const in cut_data if jet_const.size > 0]

print(cut_data)

[array([[0.97807979, 0.00117104, 0.71172398],
       [0.96379767, 0.86715605, 0.2173511 ],
       [0.65462524, 0.44441134, 0.46172768],
       [0.53445562, 0.68013254, 0.39513529],
       [0.3442667 , 0.49736153, 0.6199436 ]]), array([[0.82502873, 0.76993095, 0.98115178],
       [0.45679646, 0.5821968 , 0.87446563],
       [0.43551199, 0.2502537 , 0.69733654],
       [0.2416555 , 0.54040756, 0.17380207]]), array([[0.98650006, 0.04794429, 0.46993849],
       [0.81366201, 0.42339047, 0.04457746],
       [0.61971309, 0.37085694, 0.60514442],
       [0.53837013, 0.50864835, 0.1282322 ],
       [0.22942563, 0.85755679, 0.45045667]]), array([[0.93317273, 0.55193032, 0.11748172],
       [0.8252512 , 0.35326552, 0.83598052],
       [0.77822397, 0.19413064, 0.53467083],
       [0.52921853, 0.28063085, 0.42016388],
       [0.35457106, 0.27425754, 0.18450468],
       [0.34232631, 0.548164  , 0.43214091]]), array([[0.99595068, 0.94088614, 0.32342719],
       [0.97163663, 0.05751387, 0.68021434],
 

In [21]:
max_constituents = 6
nb_constituents = np.array([])

for jet in range(len(cut_data)):
    if cut_data[jet].shape[0] >= max_constituents:
        nb_constituents = np.append(nb_constituents, max_constituents)
        cut_data[jet] = cut_data[jet][:max_constituents, :]
    else:
        nb_constituents = np.append(nb_constituents, cut_data[jet].shape[0])
        padding_length = max_constituents - cut_data[jet].shape[0]
        cut_data[jet] = np.pad(cut_data[jet], ((0, padding_length), (0, 0)), constant_values = 0)
cut_data = np.array(cut_data)
print(cut_data)
print('\n===================\n')
print(nb_constituents)

[[[0.97807979 0.00117104 0.71172398]
  [0.96379767 0.86715605 0.2173511 ]
  [0.65462524 0.44441134 0.46172768]
  [0.53445562 0.68013254 0.39513529]
  [0.3442667  0.49736153 0.6199436 ]
  [0.         0.         0.        ]]

 [[0.82502873 0.76993095 0.98115178]
  [0.45679646 0.5821968  0.87446563]
  [0.43551199 0.2502537  0.69733654]
  [0.2416555  0.54040756 0.17380207]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 [[0.98650006 0.04794429 0.46993849]
  [0.81366201 0.42339047 0.04457746]
  [0.61971309 0.37085694 0.60514442]
  [0.53837013 0.50864835 0.1282322 ]
  [0.22942563 0.85755679 0.45045667]
  [0.         0.         0.        ]]

 [[0.93317273 0.55193032 0.11748172]
  [0.8252512  0.35326552 0.83598052]
  [0.77822397 0.19413064 0.53467083]
  [0.52921853 0.28063085 0.42016388]
  [0.35457106 0.27425754 0.18450468]
  [0.34232631 0.548164   0.43214091]]

 [[0.99595068 0.94088614 0.32342719]
  [0.97163663 0.05751387 0.68021434]
  [0.71348403 0.51383027 0.947

In [27]:
is_not_padded = np.any(cut_data, axis = 2)
print(is_not_padded)
constituent_memory = is_not_padded.sum(axis = 1)
print(constituent_memory)
# is_positive_class = [True, False, False, True, False]
# print(is_positive_class)

[[ True  True  True  True  True False]
 [ True  True  True  True False False]
 [ True  True  True  True  True False]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
[5 4 5 6 6]


In [25]:
print(cut_data[is_not_padded, :])

[[0.97807979 0.00117104 0.71172398]
 [0.96379767 0.86715605 0.2173511 ]
 [0.65462524 0.44441134 0.46172768]
 [0.53445562 0.68013254 0.39513529]
 [0.3442667  0.49736153 0.6199436 ]
 [0.82502873 0.76993095 0.98115178]
 [0.45679646 0.5821968  0.87446563]
 [0.43551199 0.2502537  0.69733654]
 [0.2416555  0.54040756 0.17380207]
 [0.98650006 0.04794429 0.46993849]
 [0.81366201 0.42339047 0.04457746]
 [0.61971309 0.37085694 0.60514442]
 [0.53837013 0.50864835 0.1282322 ]
 [0.22942563 0.85755679 0.45045667]
 [0.93317273 0.55193032 0.11748172]
 [0.8252512  0.35326552 0.83598052]
 [0.77822397 0.19413064 0.53467083]
 [0.52921853 0.28063085 0.42016388]
 [0.35457106 0.27425754 0.18450468]
 [0.34232631 0.548164   0.43214091]
 [0.99595068 0.94088614 0.32342719]
 [0.97163663 0.05751387 0.68021434]
 [0.71348403 0.51383027 0.94738157]
 [0.69386633 0.22765277 0.01291907]
 [0.65306095 0.7978226  0.1653417 ]
 [0.26906658 0.85730078 0.26580246]]


In [65]:
print(rand_class)
large_class = np.array([], dtype = int)
cut_data[1]

for i in range(len(constituent_memory)):
    print(i)
    large_class = np.append(large_class, constituent_memory[i]*[rand_class[i]])

print(large_class)

[0 4 4 1 4]
0
1
2
3
4
[0 0 0 0 0 4 4 4 4 4 4 4 4 4 1 1 1 1 1 1 4 4 4 4 4 4]


In [64]:
print(cut_data[is_not_padded, :])
print(len(cut_data[is_not_padded, :]))
print(large_class)
print(len(large_class))
print(large_class.reshape(len(large_class), 1))

np.concatenate((cut_data[is_not_padded, :], large_class.reshape(len(large_class), 1)), axis =1)

[[0.97807979 0.00117104 0.71172398]
 [0.96379767 0.86715605 0.2173511 ]
 [0.65462524 0.44441134 0.46172768]
 [0.53445562 0.68013254 0.39513529]
 [0.3442667  0.49736153 0.6199436 ]
 [0.82502873 0.76993095 0.98115178]
 [0.45679646 0.5821968  0.87446563]
 [0.43551199 0.2502537  0.69733654]
 [0.2416555  0.54040756 0.17380207]
 [0.98650006 0.04794429 0.46993849]
 [0.81366201 0.42339047 0.04457746]
 [0.61971309 0.37085694 0.60514442]
 [0.53837013 0.50864835 0.1282322 ]
 [0.22942563 0.85755679 0.45045667]
 [0.93317273 0.55193032 0.11748172]
 [0.8252512  0.35326552 0.83598052]
 [0.77822397 0.19413064 0.53467083]
 [0.52921853 0.28063085 0.42016388]
 [0.35457106 0.27425754 0.18450468]
 [0.34232631 0.548164   0.43214091]
 [0.99595068 0.94088614 0.32342719]
 [0.97163663 0.05751387 0.68021434]
 [0.71348403 0.51383027 0.94738157]
 [0.69386633 0.22765277 0.01291907]
 [0.65306095 0.7978226  0.1653417 ]
 [0.26906658 0.85730078 0.26580246]]
26
[0 0 0 0 0 4 4 4 4 4 4 4 4 4 1 1 1 1 1 1 4 4 4 4 4 4]
26
[[0

array([[9.78079792e-01, 1.17103956e-03, 7.11723978e-01, 0.00000000e+00],
       [9.63797668e-01, 8.67156052e-01, 2.17351104e-01, 0.00000000e+00],
       [6.54625239e-01, 4.44411340e-01, 4.61727682e-01, 0.00000000e+00],
       [5.34455624e-01, 6.80132537e-01, 3.95135288e-01, 0.00000000e+00],
       [3.44266700e-01, 4.97361531e-01, 6.19943596e-01, 0.00000000e+00],
       [8.25028729e-01, 7.69930948e-01, 9.81151776e-01, 4.00000000e+00],
       [4.56796461e-01, 5.82196796e-01, 8.74465627e-01, 4.00000000e+00],
       [4.35511989e-01, 2.50253701e-01, 6.97336545e-01, 4.00000000e+00],
       [2.41655498e-01, 5.40407557e-01, 1.73802067e-01, 4.00000000e+00],
       [9.86500059e-01, 4.79442895e-02, 4.69938490e-01, 4.00000000e+00],
       [8.13662006e-01, 4.23390467e-01, 4.45774552e-02, 4.00000000e+00],
       [6.19713086e-01, 3.70856942e-01, 6.05144418e-01, 4.00000000e+00],
       [5.38370134e-01, 5.08648351e-01, 1.28232204e-01, 4.00000000e+00],
       [2.29425628e-01, 8.57556793e-01, 4.50456673e

In [12]:
cut_boolean_mask = cut_data[:, :, 1] < 0.5
print(cut_boolean_mask)

[[False False False False  True  True]
 [False  True False False  True  True]
 [ True  True  True  True False  True]
 [False False  True False  True  True]
 [ True  True  True False  True  True]]


In [13]:
new_boolean_mask = cut_boolean_mask * is_not_padded
new_structure_memory = new_boolean_mask.sum(axis = 1)
print(new_boolean_mask)
print(new_structure_memory)

[[False False False False False False]
 [False  True False False False False]
 [ True  True  True  True False False]
 [False False  True False False False]
 [ True  True  True False False False]]
[0 1 4 1 3]


In [30]:
new_cut_data = np.split(cut_data[new_boolean_mask, :], np.cumsum(new_structure_memory)[:-1])
print(new_cut_data)

# new_cut_data = [jet_const for jet_const in new_cut_data if jet_const.size >0]
# print(new_cut_data)

ascending = True
order = ascending - (not ascending)

new_cut_data = [new_cut_data[i][(order*new_cut_data[i][:, 1]).argsort()] for i in range(len(new_cut_data))]

print('-----------------')
print(new_cut_data)
print(type(new_cut_data))

[array([[0.31096717, 0.19810237, 0.9584172 ]]), array([[0.55501169, 0.24169078, 0.91067052],
       [0.23784861, 0.05837725, 0.06358404],
       [0.22099701, 0.0475618 , 0.9945953 ]]), array([[0.67377265, 0.14582521, 0.25992718],
       [0.60179192, 0.02465442, 0.22187714]]), array([[0.93891831, 0.24385523, 0.26970766],
       [0.79101309, 0.18717309, 0.02891489]]), array([[0.90123358, 0.07322485, 0.19132789],
       [0.49177459, 0.12306054, 0.63115467],
       [0.40722695, 0.32317744, 0.99055728]])]
-----------------
[array([[0.31096717, 0.19810237, 0.9584172 ]]), array([[0.22099701, 0.0475618 , 0.9945953 ],
       [0.23784861, 0.05837725, 0.06358404],
       [0.55501169, 0.24169078, 0.91067052]]), array([[0.60179192, 0.02465442, 0.22187714],
       [0.67377265, 0.14582521, 0.25992718]]), array([[0.79101309, 0.18717309, 0.02891489],
       [0.93891831, 0.24385523, 0.26970766]]), array([[0.90123358, 0.07322485, 0.19132789],
       [0.49177459, 0.12306054, 0.63115467],
       [0.4072269

In [32]:
a = [jet_const[:,[0,2]]for jet_const in new_cut_data]
print(a)

[array([[0.31096717, 0.9584172 ]]), array([[0.22099701, 0.9945953 ],
       [0.23784861, 0.06358404],
       [0.55501169, 0.91067052]]), array([[0.60179192, 0.22187714],
       [0.67377265, 0.25992718]]), array([[0.79101309, 0.02891489],
       [0.93891831, 0.26970766]]), array([[0.90123358, 0.19132789],
       [0.49177459, 0.63115467],
       [0.40722695, 0.99055728]])]


In [47]:
for jet_const in new_cut_data:
    print(jet_const[:,0])
    print(jet_const[:-1,0])

[0.97871777 0.63655692 0.91614239]
[0.97871777 0.63655692]
[0.75911078 0.44960439]
[0.75911078]
[0.20231241 0.59754777]
[0.20231241]
[0.26113121 0.74083859 0.60409017 0.99859102]
[0.26113121 0.74083859 0.60409017]
[0.21209679 0.69501631 0.24753559]
[0.21209679 0.69501631]


In [46]:
means_a = [np.mean(jet_const[:,0]) for jet_const in new_cut_data]
means_b = [np.mean(jet_const[:,1]) for jet_const in new_cut_data]
means_c = [np.mean(jet_const[:,2]) for jet_const in new_cut_data]
means_a_ = [np.mean(jet_const[:-1,0]) for jet_const in new_cut_data]
means_b_ = [np.mean(jet_const[:-1,1]) for jet_const in new_cut_data]
means_c_ = [np.mean(jet_const[:-1,2]) for jet_const in new_cut_data]
sums = [np.sum(jet_const[:4,0]) for jet_const in new_cut_data]
print(means_a)
print(means_b)
print(means_c)
print(means_a_)
print(means_b_)
print(means_c_)
print(sums)
print(type(means_a))

[0.8438056940131718, 0.6043575847390479, 0.39993009000062085, 0.651162744623324, 0.3848828952524548]
[0.21508228565421253, 0.2933041124010902, 0.2545993987739518, 0.30519418829191636, 0.25061492536523694]
[0.4152671355253024, 0.9305915189512699, 0.47521143801791466, 0.8068262347149068, 0.7300975822380785]
[0.8076373484062733, 0.7591107791547588, 0.2023124058816611, 0.5353533195446221, 0.4535565497622538]
[0.10286911689738365, 0.15526971767320052, 0.16898222169179455, 0.24367609070987142, 0.1520503637342021]
[0.15779017362619163, 0.8631180130219206, 0.09879336888222601, 0.8561205298940121, 0.6278269491664584]
[2.5314170820395154, 1.2087151694780958, 0.7998601800012417, 2.604650978493296, 1.1546486857573643]
<class 'list'>


In [52]:
feature_labels  = ['a','b','c']

def create_aggregated_feature(x_data, operation, feature, nb_const = None, sorted_feature='b', sort_ascending=True):
    try:
        sorted_feature_index = feature_labels.index(sorted_feature)
    except:
        print(f"'{sorted_feature}' not found in list of features!")
        return

    order = sort_ascending - (not sort_ascending)

    sorted_data = [x_data[i][(order*x_data[i][:, sorted_feature_index]).argsort()] for i in range(len(x_data))]
    
    try:
        feature_index = feature_labels.index(feature)
    except:
        print(f"'{feature}' not found in list of features!")
        return
    
    switcher = {
        "mean": lambda: [np.mean(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
        "median": lambda: [np.median(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
        "min": lambda: [np.amin(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
        "max": lambda: [np.amax(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
        "sum": lambda: [np.sum(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
    }

    aggregated_feature = switcher.get(operation, lambda: None)()
    if aggregated_feature is None:
        raise TypeError(f"'{operation}' not found from list of operations!")
    
    return aggregated_feature

def aggregate_all_features(x_data, operation):
    agg_feature_dict = {}
    
    for feature in feature_labels:
        agg_feature_dict[f'{feature}_{operation}'] = create_aggregated_feature(x_data, operation, feature)

    return agg_feature_dict

In [53]:
alt_means_ = create_aggregated_feature(new_cut_data, 'max', 'c', 3, sorted_feature='a', sort_ascending = True)
print(alt_means_)
alt_sums_ = create_aggregated_feature(new_cut_data, 'median', 'a', 4)
print(alt_sums_)

all_means = aggregate_all_features(new_cut_data, 'mean')
for feature in all_means:
    print(f'{feature}: {all_means[feature]}')
break_test = create_aggregated_feature(new_cut_data, 'me', 'd', 2)

[0.9302210593235242, 0.9980650248806193, 0.8516295071536033, 0.948262834618327, 0.9346388483813187]
[0.9161423852269688, 0.6043575847390479, 0.39993009000062085, 0.6724643763282622, 0.24753558623285676]
a_mean: [0.8438056940131718, 0.6043575847390479, 0.39993009000062085, 0.651162744623324, 0.3848828952524548]
b_mean: [0.21508228565421253, 0.2933041124010902, 0.2545993987739518, 0.30519418829191636, 0.25061492536523694]
c_mean: [0.4152671355253024, 0.9305915189512699, 0.47521143801791466, 0.8068262347149068, 0.7300975822380785]
'd' not found in list of features!


In [110]:
max_constituents = 4
new_nb_constituents = np.array([])

for jet in range(len(new_cut_data)):
    if new_cut_data[jet].shape[0] >= max_constituents:
        new_nb_constituents = np.append(new_nb_constituents, max_constituents)
        new_cut_data[jet] = new_cut_data[jet][:max_constituents, :]
    else:
        new_nb_constituents = np.append(new_nb_constituents, new_cut_data[jet].shape[0])
        padding_length = max_constituents - new_cut_data[jet].shape[0]
        new_cut_data[jet] = np.pad(new_cut_data[jet], ((0, padding_length), (0, 0)), constant_values = -0.999)
new_cut_data = np.array(new_cut_data)
print(new_cut_data)
print('\n===================\n')
print(new_nb_constituents)

[[[ 0.62329008  0.31537603  0.98695186]
  [ 0.2092492   0.37123428  0.07122857]
  [-0.999      -0.999      -0.999     ]
  [-0.999      -0.999      -0.999     ]]

 [[ 0.61153328  0.30160817  0.08293803]
  [-0.999      -0.999      -0.999     ]
  [-0.999      -0.999      -0.999     ]
  [-0.999      -0.999      -0.999     ]]

 [[ 0.20614618  0.23781982  0.07321044]
  [ 0.29814028  0.3613127   0.68847572]
  [ 0.75464347  0.48001996  0.3304572 ]
  [-0.999      -0.999      -0.999     ]]

 [[ 0.23920947  0.05308377  0.38631762]
  [ 0.21820527  0.16563036  0.03788958]
  [ 0.31354992  0.16757342  0.09224389]
  [ 0.96516806  0.19341745  0.0067916 ]]

 [[ 0.60452188  0.16031759  0.39418248]
  [ 0.50079443  0.25102322  0.03547827]
  [ 0.22961632  0.37072405  0.34178145]
  [-0.999      -0.999      -0.999     ]]]


[2. 1. 3. 4. 3.]


In [71]:
positive_class = 't'

In [85]:
bytes(positive_class, 'utf-8')

b't'

In [2]:
feature_labels = [
        "px",
        "py",
        "pz",
        "E",
        "E_rel",
        "pT",
        "pT_rel",
        "eta",
        "eta_rel",
        "eta_rot",
        "phi",
        "phi_rel",
        "phi_rot",
        "Delta_R",
        "cos(theta)",
        "cos(theta_rel)",
    ]

In [7]:
from prepare_data_BDT import select_feature_labels

andre_features = select_feature_labels('andre')
jedinet_features = select_feature_labels('jedinet')

In [13]:
indices = []

for feature in select_feature_labels('andre'):
    index = select_feature_labels('jedinet').index(feature)
    indices.append(index)

print(indices)

[5, 8, 11]


In [7]:
import sys
import time

In [17]:
print('Starting process')

sys.stdout.write('\r')
# the exact output you're looking for:
sys.stdout.write("[%-20s] %d%%" % ('='*1, 5*1))
sys.stdout.flush()
time.sleep(0.5)

for i in range(2, 21):
    sys.stdout.write('\r')
    # the exact output you're looking for:
    sys.stdout.write("[%-20s] %d%%" % ('='*i, 5*i))
    sys.stdout.flush()
    time.sleep(0.5)

print('\nProcess complete')
    

Starting process
[====================] 100%
Process complete


In [36]:
from terminal_colors import tcols

a = True
print(tcols.FAIL+f'I just came to say {a*"hello"+(not a)*"goodbye"}'+tcols.ENDC)

I just came to say hello


In [33]:
df = pd.DataFrame()

In [34]:
df

Empty DataFrame
Columns: []
Index: []

In [35]:
df['rah'] = 69

In [37]:
df

Empty DataFrame
Columns: [rah]
Index: []

In [40]:
6 != 3

True

In [2]:
a = 5

In [4]:
b = str(a)

In [5]:
int(b)

5

In [20]:
nb_constituents = 'test'

try:
    print(f"Taking first {int(nb_constituents)} constituents")

except:
    print(f"Choosing from predified list: {nb_constituents}")

Choosing from predified list: test
