In [1]:
import numpy as np
import pandas as pd

In [25]:
data = [[1.3,6.2,7.3,], [4.2,8.1,0.3], [3.7,1.1,2.8], [13.2,8.2,3.1,], [1.3,5.1,3.9], [3.2,4.1,12.5]]

heading = ['a', 'b', 'c']

ohe_data = np.array([[0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 0, 1],
 [0, 1, 0, 0, 0]])

classes = np.array([b'g', b'q', b'w', b'z', b't'])

In [18]:
rand_data = np.random.rand(5,6,3)
#big_rand_data = np.random.rand(620000,50,16)
print(rand_data)

[[[0.02015737 0.65333542 0.3049882 ]
  [0.07820055 0.30533345 0.42605094]
  [0.74811321 0.94227505 0.63509401]
  [0.49477809 0.70577921 0.36569448]
  [0.31096717 0.19810237 0.9584172 ]
  [0.66085715 0.64821744 0.27125519]]

 [[0.22099701 0.0475618  0.9945953 ]
  [0.86491147 0.77578142 0.29422486]
  [0.23784861 0.05837725 0.06358404]
  [0.81462544 0.70656897 0.74585937]
  [0.55501169 0.24169078 0.91067052]
  [0.46560865 0.73662486 0.67947626]]

 [[0.27057806 0.7235626  0.50809365]
  [0.05604951 0.78927859 0.4489258 ]
  [0.60179192 0.02465442 0.22187714]
  [0.67377265 0.14582521 0.25992718]
  [0.70888832 0.55407199 0.38176362]
  [0.41457571 0.64307384 0.7927241 ]]

 [[0.79101309 0.18717309 0.02891489]
  [0.93016377 0.56471698 0.52062765]
  [0.17006431 0.38010276 0.88753695]
  [0.93891831 0.24385523 0.26970766]
  [0.18538437 0.47843349 0.58577088]
  [0.00288746 0.91819414 0.24850355]]

 [[0.60466892 0.81648099 0.12656615]
  [0.40722695 0.32317744 0.99055728]
  [0.62709137 0.58202249 0.496

In [19]:
ascending = False
order = ascending - (not ascending)
print(order)

-1


In [20]:
sorted_data = np.array([rand_data[i][(order*rand_data[i][:, 0]).argsort()] for i in range(len(rand_data))])
#big_sorted_data = np.asarray([big_rand_data[i][big_rand_data[i][:, 1].argsort()] for i in range(len(big_rand_data))])

print(sorted_data)
print(type(sorted_data))

[[[0.74811321 0.94227505 0.63509401]
  [0.66085715 0.64821744 0.27125519]
  [0.49477809 0.70577921 0.36569448]
  [0.31096717 0.19810237 0.9584172 ]
  [0.07820055 0.30533345 0.42605094]
  [0.02015737 0.65333542 0.3049882 ]]

 [[0.86491147 0.77578142 0.29422486]
  [0.81462544 0.70656897 0.74585937]
  [0.55501169 0.24169078 0.91067052]
  [0.46560865 0.73662486 0.67947626]
  [0.23784861 0.05837725 0.06358404]
  [0.22099701 0.0475618  0.9945953 ]]

 [[0.70888832 0.55407199 0.38176362]
  [0.67377265 0.14582521 0.25992718]
  [0.60179192 0.02465442 0.22187714]
  [0.41457571 0.64307384 0.7927241 ]
  [0.27057806 0.7235626  0.50809365]
  [0.05604951 0.78927859 0.4489258 ]]

 [[0.93891831 0.24385523 0.26970766]
  [0.93016377 0.56471698 0.52062765]
  [0.79101309 0.18717309 0.02891489]
  [0.18538437 0.47843349 0.58577088]
  [0.17006431 0.38010276 0.88753695]
  [0.00288746 0.91819414 0.24850355]]

 [[0.90123358 0.07322485 0.19132789]
  [0.62709137 0.58202249 0.49660141]
  [0.60466892 0.81648099 0.126

In [21]:
boolean_index = [True, False, False, True, False]

print(sorted_data[:,:,1][boolean_index].flatten())

[0.94227505 0.64821744 0.70577921 0.19810237 0.30533345 0.65333542
 0.24385523 0.56471698 0.18717309 0.47843349 0.38010276 0.91819414]


In [22]:
print(boolean_index)
print(1*(boolean_index))

[True, False, False, True, False]
[True, False, False, True, False]


In [23]:
boolean_mask = sorted_data[:, :, 0] > 0.2
structure_memory = boolean_mask.sum(axis=1)

In [24]:
print(boolean_mask)
print(structure_memory)
print(np.mean(structure_memory))

[[ True  True  True  True False False]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True False]
 [ True  True  True False False False]
 [ True  True  True  True  True False]]
[4 6 5 3 5]
4.6


In [25]:
cut_data = np.split(sorted_data[boolean_mask, :], np.cumsum(structure_memory)[:-1])

print(cut_data)
print('\n================\n')
cut_data = [jet_const for jet_const in cut_data if jet_const.size > 0]

print(cut_data)

[array([[0.74811321, 0.94227505, 0.63509401],
       [0.66085715, 0.64821744, 0.27125519],
       [0.49477809, 0.70577921, 0.36569448],
       [0.31096717, 0.19810237, 0.9584172 ]]), array([[0.86491147, 0.77578142, 0.29422486],
       [0.81462544, 0.70656897, 0.74585937],
       [0.55501169, 0.24169078, 0.91067052],
       [0.46560865, 0.73662486, 0.67947626],
       [0.23784861, 0.05837725, 0.06358404],
       [0.22099701, 0.0475618 , 0.9945953 ]]), array([[0.70888832, 0.55407199, 0.38176362],
       [0.67377265, 0.14582521, 0.25992718],
       [0.60179192, 0.02465442, 0.22187714],
       [0.41457571, 0.64307384, 0.7927241 ],
       [0.27057806, 0.7235626 , 0.50809365]]), array([[0.93891831, 0.24385523, 0.26970766],
       [0.93016377, 0.56471698, 0.52062765],
       [0.79101309, 0.18717309, 0.02891489]]), array([[0.90123358, 0.07322485, 0.19132789],
       [0.62709137, 0.58202249, 0.49660141],
       [0.60466892, 0.81648099, 0.12656615],
       [0.49177459, 0.12306054, 0.63115467],
 

In [26]:
max_constituents = 6
nb_constituents = np.array([])

for jet in range(len(cut_data)):
    if cut_data[jet].shape[0] >= max_constituents:
        nb_constituents = np.append(nb_constituents, max_constituents)
        cut_data[jet] = cut_data[jet][:max_constituents, :]
    else:
        nb_constituents = np.append(nb_constituents, cut_data[jet].shape[0])
        padding_length = max_constituents - cut_data[jet].shape[0]
        cut_data[jet] = np.pad(cut_data[jet], ((0, padding_length), (0, 0)), constant_values = 0)
cut_data = np.array(cut_data)
print(cut_data)
print('\n===================\n')
print(nb_constituents)

[[[0.74811321 0.94227505 0.63509401]
  [0.66085715 0.64821744 0.27125519]
  [0.49477809 0.70577921 0.36569448]
  [0.31096717 0.19810237 0.9584172 ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 [[0.86491147 0.77578142 0.29422486]
  [0.81462544 0.70656897 0.74585937]
  [0.55501169 0.24169078 0.91067052]
  [0.46560865 0.73662486 0.67947626]
  [0.23784861 0.05837725 0.06358404]
  [0.22099701 0.0475618  0.9945953 ]]

 [[0.70888832 0.55407199 0.38176362]
  [0.67377265 0.14582521 0.25992718]
  [0.60179192 0.02465442 0.22187714]
  [0.41457571 0.64307384 0.7927241 ]
  [0.27057806 0.7235626  0.50809365]
  [0.         0.         0.        ]]

 [[0.93891831 0.24385523 0.26970766]
  [0.93016377 0.56471698 0.52062765]
  [0.79101309 0.18717309 0.02891489]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 [[0.90123358 0.07322485 0.19132789]
  [0.62709137 0.58202249 0.49660141]
  [0.60466892 0.81648099 0.126

In [27]:
is_not_padded = np.any(cut_data, axis = 2)
print(is_not_padded)
# is_positive_class = [True, False, False, True, False]
# print(is_positive_class)

[[ True  True  True  True False False]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True False]
 [ True  True  True False False False]
 [ True  True  True  True  True False]]


In [28]:
cut_boolean_mask = cut_data[:, :, 1] < 0.5
print(cut_boolean_mask)

[[False False False  True  True  True]
 [False False  True False  True  True]
 [False  True  True False False  True]
 [ True False  True  True  True  True]
 [ True False False  True  True  True]]


In [29]:
new_boolean_mask = cut_boolean_mask * is_not_padded
new_structure_memory = new_boolean_mask.sum(axis = 1)
print(new_boolean_mask)
print(new_structure_memory)

[[False False False  True False False]
 [False False  True False  True  True]
 [False  True  True False False False]
 [ True False  True False False False]
 [ True False False  True  True False]]
[1 3 2 2 3]


In [30]:
new_cut_data = np.split(cut_data[new_boolean_mask, :], np.cumsum(new_structure_memory)[:-1])
print(new_cut_data)

# new_cut_data = [jet_const for jet_const in new_cut_data if jet_const.size >0]
# print(new_cut_data)

ascending = True
order = ascending - (not ascending)

new_cut_data = [new_cut_data[i][(order*new_cut_data[i][:, 1]).argsort()] for i in range(len(new_cut_data))]

print('-----------------')
print(new_cut_data)
print(type(new_cut_data))

[array([[0.31096717, 0.19810237, 0.9584172 ]]), array([[0.55501169, 0.24169078, 0.91067052],
       [0.23784861, 0.05837725, 0.06358404],
       [0.22099701, 0.0475618 , 0.9945953 ]]), array([[0.67377265, 0.14582521, 0.25992718],
       [0.60179192, 0.02465442, 0.22187714]]), array([[0.93891831, 0.24385523, 0.26970766],
       [0.79101309, 0.18717309, 0.02891489]]), array([[0.90123358, 0.07322485, 0.19132789],
       [0.49177459, 0.12306054, 0.63115467],
       [0.40722695, 0.32317744, 0.99055728]])]
-----------------
[array([[0.31096717, 0.19810237, 0.9584172 ]]), array([[0.22099701, 0.0475618 , 0.9945953 ],
       [0.23784861, 0.05837725, 0.06358404],
       [0.55501169, 0.24169078, 0.91067052]]), array([[0.60179192, 0.02465442, 0.22187714],
       [0.67377265, 0.14582521, 0.25992718]]), array([[0.79101309, 0.18717309, 0.02891489],
       [0.93891831, 0.24385523, 0.26970766]]), array([[0.90123358, 0.07322485, 0.19132789],
       [0.49177459, 0.12306054, 0.63115467],
       [0.4072269

In [32]:
a = [jet_const[:,[0,2]]for jet_const in new_cut_data]
print(a)

[array([[0.31096717, 0.9584172 ]]), array([[0.22099701, 0.9945953 ],
       [0.23784861, 0.06358404],
       [0.55501169, 0.91067052]]), array([[0.60179192, 0.22187714],
       [0.67377265, 0.25992718]]), array([[0.79101309, 0.02891489],
       [0.93891831, 0.26970766]]), array([[0.90123358, 0.19132789],
       [0.49177459, 0.63115467],
       [0.40722695, 0.99055728]])]


In [47]:
for jet_const in new_cut_data:
    print(jet_const[:,0])
    print(jet_const[:-1,0])

[0.97871777 0.63655692 0.91614239]
[0.97871777 0.63655692]
[0.75911078 0.44960439]
[0.75911078]
[0.20231241 0.59754777]
[0.20231241]
[0.26113121 0.74083859 0.60409017 0.99859102]
[0.26113121 0.74083859 0.60409017]
[0.21209679 0.69501631 0.24753559]
[0.21209679 0.69501631]


In [46]:
means_a = [np.mean(jet_const[:,0]) for jet_const in new_cut_data]
means_b = [np.mean(jet_const[:,1]) for jet_const in new_cut_data]
means_c = [np.mean(jet_const[:,2]) for jet_const in new_cut_data]
means_a_ = [np.mean(jet_const[:-1,0]) for jet_const in new_cut_data]
means_b_ = [np.mean(jet_const[:-1,1]) for jet_const in new_cut_data]
means_c_ = [np.mean(jet_const[:-1,2]) for jet_const in new_cut_data]
sums = [np.sum(jet_const[:4,0]) for jet_const in new_cut_data]
print(means_a)
print(means_b)
print(means_c)
print(means_a_)
print(means_b_)
print(means_c_)
print(sums)
print(type(means_a))

[0.8438056940131718, 0.6043575847390479, 0.39993009000062085, 0.651162744623324, 0.3848828952524548]
[0.21508228565421253, 0.2933041124010902, 0.2545993987739518, 0.30519418829191636, 0.25061492536523694]
[0.4152671355253024, 0.9305915189512699, 0.47521143801791466, 0.8068262347149068, 0.7300975822380785]
[0.8076373484062733, 0.7591107791547588, 0.2023124058816611, 0.5353533195446221, 0.4535565497622538]
[0.10286911689738365, 0.15526971767320052, 0.16898222169179455, 0.24367609070987142, 0.1520503637342021]
[0.15779017362619163, 0.8631180130219206, 0.09879336888222601, 0.8561205298940121, 0.6278269491664584]
[2.5314170820395154, 1.2087151694780958, 0.7998601800012417, 2.604650978493296, 1.1546486857573643]
<class 'list'>


In [52]:
feature_labels  = ['a','b','c']

def create_aggregated_feature(x_data, operation, feature, nb_const = None, sorted_feature='b', sort_ascending=True):
    try:
        sorted_feature_index = feature_labels.index(sorted_feature)
    except:
        print(f"'{sorted_feature}' not found in list of features!")
        return

    order = sort_ascending - (not sort_ascending)

    sorted_data = [x_data[i][(order*x_data[i][:, sorted_feature_index]).argsort()] for i in range(len(x_data))]
    
    try:
        feature_index = feature_labels.index(feature)
    except:
        print(f"'{feature}' not found in list of features!")
        return
    
    switcher = {
        "mean": lambda: [np.mean(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
        "median": lambda: [np.median(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
        "min": lambda: [np.amin(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
        "max": lambda: [np.amax(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
        "sum": lambda: [np.sum(jet_const[:nb_const,feature_index]) for jet_const in sorted_data],
    }

    aggregated_feature = switcher.get(operation, lambda: None)()
    if aggregated_feature is None:
        raise TypeError(f"'{operation}' not found from list of operations!")
    
    return aggregated_feature

def aggregate_all_features(x_data, operation):
    agg_feature_dict = {}
    
    for feature in feature_labels:
        agg_feature_dict[f'{feature}_{operation}'] = create_aggregated_feature(x_data, operation, feature)

    return agg_feature_dict

In [53]:
alt_means_ = create_aggregated_feature(new_cut_data, 'max', 'c', 3, sorted_feature='a', sort_ascending = True)
print(alt_means_)
alt_sums_ = create_aggregated_feature(new_cut_data, 'median', 'a', 4)
print(alt_sums_)

all_means = aggregate_all_features(new_cut_data, 'mean')
for feature in all_means:
    print(f'{feature}: {all_means[feature]}')
break_test = create_aggregated_feature(new_cut_data, 'me', 'd', 2)

[0.9302210593235242, 0.9980650248806193, 0.8516295071536033, 0.948262834618327, 0.9346388483813187]
[0.9161423852269688, 0.6043575847390479, 0.39993009000062085, 0.6724643763282622, 0.24753558623285676]
a_mean: [0.8438056940131718, 0.6043575847390479, 0.39993009000062085, 0.651162744623324, 0.3848828952524548]
b_mean: [0.21508228565421253, 0.2933041124010902, 0.2545993987739518, 0.30519418829191636, 0.25061492536523694]
c_mean: [0.4152671355253024, 0.9305915189512699, 0.47521143801791466, 0.8068262347149068, 0.7300975822380785]
'd' not found in list of features!


In [110]:
max_constituents = 4
new_nb_constituents = np.array([])

for jet in range(len(new_cut_data)):
    if new_cut_data[jet].shape[0] >= max_constituents:
        new_nb_constituents = np.append(new_nb_constituents, max_constituents)
        new_cut_data[jet] = new_cut_data[jet][:max_constituents, :]
    else:
        new_nb_constituents = np.append(new_nb_constituents, new_cut_data[jet].shape[0])
        padding_length = max_constituents - new_cut_data[jet].shape[0]
        new_cut_data[jet] = np.pad(new_cut_data[jet], ((0, padding_length), (0, 0)), constant_values = -0.999)
new_cut_data = np.array(new_cut_data)
print(new_cut_data)
print('\n===================\n')
print(new_nb_constituents)

[[[ 0.62329008  0.31537603  0.98695186]
  [ 0.2092492   0.37123428  0.07122857]
  [-0.999      -0.999      -0.999     ]
  [-0.999      -0.999      -0.999     ]]

 [[ 0.61153328  0.30160817  0.08293803]
  [-0.999      -0.999      -0.999     ]
  [-0.999      -0.999      -0.999     ]
  [-0.999      -0.999      -0.999     ]]

 [[ 0.20614618  0.23781982  0.07321044]
  [ 0.29814028  0.3613127   0.68847572]
  [ 0.75464347  0.48001996  0.3304572 ]
  [-0.999      -0.999      -0.999     ]]

 [[ 0.23920947  0.05308377  0.38631762]
  [ 0.21820527  0.16563036  0.03788958]
  [ 0.31354992  0.16757342  0.09224389]
  [ 0.96516806  0.19341745  0.0067916 ]]

 [[ 0.60452188  0.16031759  0.39418248]
  [ 0.50079443  0.25102322  0.03547827]
  [ 0.22961632  0.37072405  0.34178145]
  [-0.999      -0.999      -0.999     ]]]


[2. 1. 3. 4. 3.]


In [71]:
positive_class = 't'

In [85]:
bytes(positive_class, 'utf-8')

b't'

In [2]:
feature_labels = [
        "px",
        "py",
        "pz",
        "E",
        "E_rel",
        "pT",
        "pT_rel",
        "eta",
        "eta_rel",
        "eta_rot",
        "phi",
        "phi_rel",
        "phi_rot",
        "Delta_R",
        "cos(theta)",
        "cos(theta_rel)",
    ]

In [7]:
from prepare_data_BDT import select_feature_labels

andre_features = select_feature_labels('andre')
jedinet_features = select_feature_labels('jedinet')

In [13]:
indices = []

for feature in select_feature_labels('andre'):
    index = select_feature_labels('jedinet').index(feature)
    indices.append(index)

print(indices)

[5, 8, 11]


In [7]:
import sys
import time

In [17]:
print('Starting process')

sys.stdout.write('\r')
# the exact output you're looking for:
sys.stdout.write("[%-20s] %d%%" % ('='*1, 5*1))
sys.stdout.flush()
time.sleep(0.5)

for i in range(2, 21):
    sys.stdout.write('\r')
    # the exact output you're looking for:
    sys.stdout.write("[%-20s] %d%%" % ('='*i, 5*i))
    sys.stdout.flush()
    time.sleep(0.5)

print('\nProcess complete')
    

Starting process
[====================] 100%
Process complete


In [36]:
from terminal_colors import tcols

a = True
print(tcols.FAIL+f'I just came to say {a*"hello"+(not a)*"goodbye"}'+tcols.ENDC)

I just came to say hello


In [33]:
df = pd.DataFrame()

In [34]:
df

Empty DataFrame
Columns: []
Index: []

In [35]:
df['rah'] = 69

In [37]:
df

Empty DataFrame
Columns: [rah]
Index: []

In [40]:
6 != 3

True

In [2]:
a = 5

In [4]:
b = str(a)

In [5]:
int(b)

5

In [20]:
nb_constituents = 'test'

try:
    print(f"Taking first {int(nb_constituents)} constituents")

except:
    print(f"Choosing from predified list: {nb_constituents}")

Choosing from predified list: test
